#!/usr/bin/env bun
/**
 * CLI.BUNX.AGE - Enterprise Security Policy Inspector
 * Prints active bunfig.toml security settings as YAML
 * CONFIG.BUNFIG.SECURITY - Enterprise policy controls
 */

import { readFileSync } from "fs";

// CONFIG.BUNFIG.SECURITY - Read and parse bunfig.toml
function loadBunfig() {
  try {
    const bunfigContent = readFileSync("bunfig.toml", "utf-8");

    // Use a simple parser since Bun doesn't have built-in TOML yet
    const config: any = {};
    let currentSection = "";

    const lines = bunfigContent.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
        currentSection = trimmed.slice(1, -1);
        config[currentSection] = {};
      } else if (trimmed.includes('=')) {
        const [key, ...valueParts] = trimmed.split('=');
        let value = valueParts.join('=').trim();

        if (currentSection) {
          // Parse different value types
          if (value === 'true') {
            config[currentSection][key.trim()] = true;
          } else if (value === 'false') {
            config[currentSection][key.trim()] = false;
          } else if (!isNaN(Number(value))) {
            config[currentSection][key.trim()] = Number(value);
          } else if (value.startsWith('"') && value.endsWith('"')) {
            config[currentSection][key.trim()] = value.slice(1, -1);
          } else {
            config[currentSection][key.trim()] = value;
          }
        }
      }
    }

    return config;
  } catch (error) {
    console.error("Failed to read bunfig.toml:", error);
    process.exit(1);
  }
}

// Main execution
const bunfig = loadBunfig();

// Filter to security-related sections
const securitySections = {
  install: bunfig.install,
  "install.registry": bunfig["install.registry"],
  "install.scoped-tokens": bunfig["install.scoped-tokens"],
  "install.excludes": bunfig["install.excludes"],
  "install.security": bunfig["install.security"]
};

// Output as YAML-style format
console.log("# 🔒 Enterprise Security Policy Configuration");
console.log("# CONFIG.BUNFIG.SECURITY - Active policy settings");
console.log("# Generated by bun run security:policy");
console.log("");

for (const [section, values] of Object.entries(securitySections)) {
  if (values) {
    console.log(`${section}:`);
    for (const [key, value] of Object.entries(values as any)) {
      console.log(`  ${key}: ${JSON.stringify(value)}`);
    }
    console.log("");
  }
}

// Add human-readable summary
console.log("# 📊 Policy Summary:");
if (securitySections.install?.minimumReleaseAge) {
  const days = Math.floor(securitySections.install.minimumReleaseAge / 86400);
  console.log(`# - Minimum release age: ${days} days (${securitySections.install.minimumReleaseAge}s)`);
  console.log("# - MIN_RELEASE_AGE: Prevents installation of packages newer than threshold");
}
if (securitySections["install.registry"]) {
  const registries = Object.keys(securitySections["install.registry"]).length;
  console.log(`# - Registry mappings: ${registries} scopes configured`);
}
if (securitySections["install.scoped-tokens"]) {
  const tokens = Object.keys(securitySections["install.scoped-tokens"]).length;
  console.log(`# - Scoped tokens: ${tokens} authentication tokens configured`);
}
if (securitySections["install.excludes"]) {
  const excludes = Object.keys(securitySections["install.excludes"]).length;
  console.log(`# - Package excludes: ${excludes} packages blocked`);
}
