import React, { useEffect, useState } from "react";

// Import virtual files (will be generated by bun.config.ts)
// import { BUILD_CONFIG, PORT_CONFIG } from "../build-config";
// import { THEME } from "../theme/colors";
// import { BUILD_ID, BUILD_TIME, BUN_VERSION, BUNDLE_SIZE, IS_COMPILED, TARGET } from "../build-info";
// import { mockFiles, mockArchive, mockApiResponse } from "../api/mock-responses";
// import { FileAnalyzerClient } from "../api/generated-client";

// Temporary hardcoded values until virtual files are fixed
const BUILD_CONFIG = {
  bunVersion: "1.3.6",
  buildTime: Date.now(),
  buildId: "build-" + Math.random().toString(36).substr(2, 9),
  debug: true,
  version: "1.0.0",
  apiUrl: "http://localhost:3007",
  frontendUrl: "http://localhost:3879",
};

const PORT_CONFIG = {
  frontend: "3879",
  api: "3007",
  environment: "development",
};

const THEME = {
  colors: {
    primary: "#3b82f6",
    success: "#22c55e",
    warning: "#f59e0b",
    error: "#ef4444",
    info: "#06b6d4",
  },
  gradients: {
    primary: "linear-gradient(135deg, #3b82f6, #22c55e)",
    ocean: "linear-gradient(135deg, #06b6d4, #3b82f6)",
  },
  semantic: {
    env: "#059669",
    const: "#1d4ed8",
    runtime: "#d97706",
    dep: "#7c3aed",
    config: "#0891b2",
  },
};

const BUILD_ID = "build-" + Math.random().toString(36).substr(2, 9);
const BUILD_TIME = Date.now();
const BUN_VERSION = "1.3.6";
const BUNDLE_SIZE = "1.1 MB";
const IS_COMPILED = false;
const TARGET = "browser";

export const DevDashboard = () => {
  const [stats, setStats] = useState({
    bunVersion: BUILD_CONFIG.bunVersion,
    hmrEnabled: false,
    buildTime: new Date(BUILD_CONFIG.buildTime).toLocaleTimeString(),
    environment: BUILD_CONFIG.debug ? "development" : "production",
    port: PORT_CONFIG.frontend,
    apiPort: PORT_CONFIG.api,
    buildId: BUILD_CONFIG.buildId,
    version: BUILD_CONFIG.version,
  });
  
  const refresh = () => {
    setStats(prev => ({
      ...prev,
      hmrEnabled: !!import.meta.hot,
      buildTime: new Date().toLocaleTimeString(),
    }));
  };
  
  useEffect(() => {
    refresh();
    
    // Colorful logging with theme
    console.log(
      `%c=== Bun v${stats.bunVersion} Enhanced Dev Dashboard ===`, 
      `color: ${THEME.colors.primary}; font-size: 16px; font-weight: bold`
    );
    console.log(
      `%cBuild ID: ${stats.buildId}`, 
      `color: ${THEME.colors.info}`
    );
    console.log(
      `%cHMR: ${import.meta.hot ? "enabled" : "disabled"}`,
      `color: ${import.meta.hot ? THEME.colors.success : THEME.colors.error}` 
    );
    console.log(
      `%cVirtual Files: 🔄 Setting up...`,
      `color: ${THEME.semantic.config}`
    );
    
    // Auto-refresh every 5 seconds
    const interval = setInterval(refresh, 5000);
    return () => clearInterval(interval);
  }, []);
  
  // Enhanced configuration matrix (showing the architecture we're building)
  const configMatrix = [
    {
      category: "🌐 Enhanced Server Configuration",
      items: [
        { name: "Frontend Port", value: stats.port, type: "env", source: "PORT (configured)" },
        { name: "API Server Port", value: stats.apiPort, type: "env", source: "API_PORT (configured)" },
        { name: "Frontend URL", value: BUILD_CONFIG.frontendUrl, type: "const", source: "build-config.ts" },
        { name: "API Base URL", value: BUILD_CONFIG.apiUrl, type: "const", source: "build-config.ts" },
      ]
    },
    {
      category: "🔧 Advanced Build Configuration",
      items: [
        { name: "Environment", value: stats.environment.toUpperCase(), type: "env", source: "NODE_ENV" },
        { name: "Build Target", value: "Browser (ESM)", type: "const", source: "bun.config.ts" },
        { name: "HMR Enabled", value: stats.hmrEnabled ? "YES" : "NO", type: "runtime", source: "import.meta.hot" },
        { name: "Virtual Files", value: "PENDING", type: "config", source: "bun.config.ts files option" },
        { name: "Build Time", value: stats.buildTime, type: "runtime", source: "Date.now()" },
        { name: "Build ID", value: stats.buildId.slice(0, 8) + "...", type: "const", source: "Bun.randomUUIDv7()" },
      ]
    },
    {
      category: "📦 Package & Dependencies",
      items: [
        { name: "App Version", value: stats.version, type: "const", source: "package.json" },
        { name: "Bun Version", value: stats.bunVersion, type: "const", source: "Bun.version" },
        { name: "React Version", value: "18.2.0", type: "dep", source: "package.json" },
        { name: "TypeScript", value: "5.x", type: "dep", source: "devDependencies" },
        { name: "Hono Framework", value: "3.0.0", type: "dep", source: "dependencies" },
      ]
    },
    {
      category: "🎨 Theme & Color System",
      items: [
        { name: "Primary Color", value: THEME.colors.primary, type: "const", source: "design system" },
        { name: "Success Color", value: THEME.colors.success, type: "const", source: "design system" },
        { name: "Warning Color", value: THEME.colors.warning, type: "const", source: "design system" },
        { name: "Error Color", value: THEME.colors.error, type: "const", source: "design system" },
        { name: "Info Color", value: THEME.colors.info, type: "const", source: "design system" },
      ]
    },
    {
      category: "🚀 Bun v1.3.6+ Features",
      items: [
        { name: "React Fast Refresh", value: "NATIVE", type: "config", source: "reactFastRefresh: true" },
        { name: "Metafile Analysis", value: "ENABLED", type: "config", source: "metafile: true" },
        { name: "Virtual Modules", value: "SETTING UP", type: "config", source: "files: {...}" },
        { name: "Response.json()", value: "3.5x FASTER", type: "const", source: "Bun optimization" },
        { name: "Color Utilities", value: "WCAG AA", type: "const", source: "Bun.color()" },
        { name: "Cross-Compilation", value: "READY", type: "config", source: "--compile flag" },
      ]
    },
    {
      category: "🔐 Security & Performance",
      items: [
        { name: "CORS Origin", value: BUILD_CONFIG.frontendUrl, type: "env", source: "computed" },
        { name: "CORS Methods", value: "GET, POST", type: "const", source: "api/index.ts" },
        { name: "Service Worker", value: "v2 (network-first)", type: "config", source: "sw.js" },
        { name: "Cache Strategy", value: "network-first (dev)", type: "config", source: "sw.js" },
        { name: "Bundle Analysis", value: "METAFILE", type: "config", source: "build output" },
      ]
    }
  ];

  const getTypeColor = (type: string) => {
    switch (type) {
      case "env": return THEME.semantic.env;
      case "const": return THEME.semantic.const;
      case "runtime": return THEME.semantic.runtime;
      case "dep": return THEME.semantic.dep;
      case "config": return THEME.semantic.config;
      default: return "#4b5563";
    }
  };

  const getTypeBgColor = (type: string) => {
    switch (type) {
      case "env": return "#d1fae5";
      case "const": return "#dbeafe";
      case "runtime": return "#fed7aa";
      case "dep": return "#e9d5ff";
      case "config": return "#cffafe";
      default: return "#e5e7eb";
    }
  };

  const getTypeLabel = (type: string) => {
    switch (type) {
      case "env": return "ENV";
      case "const": return "CONST";
      case "runtime": return "RUNTIME";
      case "dep": return "DEP";
      case "config": return "CONFIG";
      default: return "UNKNOWN";
    }
  };
  
  return (
    <div style={{
      background: THEME.colors.primary,
      color: "#fff",
      padding: "1.5rem",
      borderRadius: "0.5rem",
      margin: "1rem 0",
      boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
      backgroundImage: THEME.gradients.primary,
    }}>
      <h2 style={{
        fontSize: "1.5rem",
        fontWeight: "bold",
        marginBottom: "1rem",
        color: "#fff",
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
      }}>📊 Bun v{stats.bunVersion} Enhanced Architecture</h2>
      
      <div style={{ display: "grid", gap: "0.75rem", marginBottom: "1rem" }}>
        <Stat label="🔥 HMR Status" value={stats.hmrEnabled ? "ON" : "OFF"} color={stats.hmrEnabled ? THEME.colors.success : THEME.colors.error} />
        <Stat label="🌐 Frontend Port" value={stats.port} color={THEME.colors.info} />
        <Stat label="📡 API Port" value={stats.apiPort} color={THEME.colors.warning} />
        <Stat label="⚙️ Environment" value={stats.environment.toUpperCase()} color={THEME.semantic.config} />
        <Stat label="🕐 Build Time" value={stats.buildTime} color={THEME.semantic.dep} />
        <Stat label="🆔 Build ID" value={stats.buildId.slice(0, 8)} color={THEME.colors.primary} />
      </div>
      
      {/* Enhanced Configuration Matrix Table */}
      <div style={{
        background: "rgba(255, 255, 255, 0.95)",
        padding: "1.5rem",
        borderRadius: "0.5rem",
        marginBottom: "1rem",
        border: `1px solid ${THEME.colors.primary}20`,
        boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
      }}>
        <h3 style={{
          fontSize: "1.25rem",
          fontWeight: "bold",
          marginBottom: "1.5rem",
          color: "#1e293b",
          borderBottom: `2px solid ${THEME.colors.primary}`,
          paddingBottom: "0.5rem",
        }}>🔧 Enhanced Configuration Matrix (v1.3.6+ Architecture)</h3>
        
        {configMatrix.map((section, sectionIndex) => (
          <div key={sectionIndex} style={{ marginBottom: "2rem" }}>
            <h4 style={{
              fontSize: "1.125rem",
              fontWeight: "bold",
              marginBottom: "1rem",
              color: "#374151",
              background: THEME.gradients.ocean,
              padding: "0.75rem 1rem",
              borderRadius: "0.375rem",
              borderLeft: `4px solid ${THEME.colors.primary}`,
            }}>{section.category}</h4>
            
            <div style={{
              background: "#ffffff",
              borderRadius: "0.375rem",
              overflow: "hidden",
              border: "1px solid #e5e7eb",
              boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
            }}>
              {/* Table Header */}
              <div style={{
                display: "grid",
                gridTemplateColumns: "2fr 1fr 1fr 2fr",
                background: THEME.gradients.primary,
                color: "#ffffff",
                fontWeight: "bold",
                padding: "1rem",
                fontSize: "0.875rem",
              }}>
                <div style={{ paddingLeft: "0.5rem" }}>Variable</div>
                <div style={{ textAlign: "center" }}>Value</div>
                <div style={{ textAlign: "center" }}>Type</div>
                <div style={{ paddingLeft: "0.5rem" }}>Source</div>
              </div>
              
              {/* Table Rows */}
              {section.items.map((item, itemIndex) => (
                <div key={itemIndex} style={{
                  display: "grid",
                  gridTemplateColumns: "2fr 1fr 1fr 2fr",
                  padding: "0.75rem 1rem",
                  fontSize: "0.875rem",
                  borderBottom: itemIndex < section.items.length - 1 ? "1px solid #f3f4f6" : "none",
                  background: itemIndex % 2 === 0 ? "#ffffff" : "#f9fafb",
                  transition: "background-color 0.2s ease",
                }}>
                  <div style={{ 
                    color: "#374151", 
                    fontWeight: "600",
                    padding: "0.25rem 0.5rem",
                    display: "flex",
                    alignItems: "center"
                  }}>
                    {item.name}
                  </div>
                  <div style={{ 
                    color: "#1e293b", 
                    fontWeight: "bold",
                    padding: "0.25rem 0",
                    fontFamily: "'Fira Code', 'Courier New', monospace",
                    textAlign: "center",
                    background: getTypeBgColor(item.type),
                    borderRadius: "0.25rem",
                    margin: "0.25rem 0",
                    border: `1px solid ${getTypeColor(item.type)}20`,
                  }}>{item.value}</div>
                  <div style={{ 
                    padding: "0.25rem 0",
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center"
                  }}>
                    <span style={{
                      background: getTypeColor(item.type),
                      color: "#ffffff",
                      padding: "0.25rem 0.75rem",
                      borderRadius: "0.375rem",
                      fontSize: "0.75rem",
                      fontWeight: "bold",
                      textTransform: "uppercase",
                      letterSpacing: "0.05em",
                      boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                    }}>{getTypeLabel(item.type)}</span>
                  </div>
                  <div style={{ 
                    color: "#6b7280", 
                    padding: "0.25rem 0.5rem",
                    fontStyle: "italic",
                    fontSize: "0.8rem",
                    display: "flex",
                    alignItems: "center"
                  }}>{item.source}</div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
      
      <div style={{
        background: "rgba(255, 255, 255, 0.1)",
        padding: "0.75rem",
        borderRadius: "0.25rem",
        marginBottom: "1rem",
      }}>
        <div style={{ fontSize: "0.875rem", marginBottom: "0.5rem" }}>
          <strong>Bun Version:</strong> {stats.bunVersion}
        </div>
        <div style={{ fontSize: "0.875rem", marginBottom: "0.5rem" }}>
          <strong>Build ID:</strong> {stats.buildId}
        </div>
        <div style={{ fontSize: "0.875rem", marginBottom: "0.5rem" }}>
          <strong>Virtual Files:</strong> 🔄 Setting up...
        </div>
        <div style={{ fontSize: "0.875rem" }}>
          <strong>Architecture:</strong> Bun v1.3.6+ Enhanced
        </div>
      </div>
      
      <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
        <button 
          onClick={refresh}
          style={{
            background: THEME.colors.success,
            color: "#fff",
            border: "none",
            padding: "0.75rem 1.5rem",
            borderRadius: "0.25rem",
            cursor: "pointer",
            fontWeight: "bold",
            fontSize: "0.875rem",
          }}
        >
          🔄 Refresh Now
        </button>
        
        <button 
          onClick={() => window.location.reload()}
          style={{
            background: THEME.colors.warning,
            color: "#fff",
            border: "none",
            padding: "0.75rem 1.5rem",
            borderRadius: "0.25rem",
            cursor: "pointer",
            fontWeight: "bold",
            fontSize: "0.875rem",
          }}
        >
          🔃 Hard Reload
        </button>
      </div>
    </div>
  );
};

const Stat = ({ label, value, color }: { label: string; value: string; color: string }) => (
  <div style={{
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.75rem",
    background: "rgba(255, 255, 255, 0.1)",
    borderRadius: "0.25rem",
    border: `1px solid ${color}20`,
    backdropFilter: "blur(10px)",
  }}>
    <span style={{ fontSize: "0.875rem" }}>{label}</span>
    <span style={{ 
      fontWeight: "bold", 
      fontSize: "1rem",
      color: color,
      textShadow: "0 1px 2px rgba(0,0,0,0.1)"
    }}>{value}</span>
  </div>
);
