
import React, { useState, useMemo } from 'react';
import { Settings, Copy, Info, Check, Trash2, Plus, Zap, Shield, Beaker, Package, Terminal, Layers, X, AlertCircle, FileJson, Cpu, Microscope, PlayCircle, Terminal as TerminalIcon } from 'lucide-react';

export const BunfigBuilder: React.FC = () => {
  const [config, setConfig] = useState({
    smol: false,
    telemetry: true,
    logLevel: 'debug',
    preload: ['./preload.ts'],
    configVersion: 1,
    disableNativeLinker: false,
    cpuProf: false,
    cpuProfName: 'profile.cpuprofile',
    cpuProfDir: './profiles',
    test: {
      coverage: true,
      randomize: false,
      rerunEach: 0,
      passWithNoTests: true,
      onlyFailures: false
    },
    install: {
      linker: 'isolated',
      production: false,
      frozenLockfile: false,
      saveTextLockfile: true,
      publicHoistPattern: ['@types*', '*eslint*'],
      hoistPattern: ['@types*', '*eslint*']
    }
  });

  const [newPattern, setNewPattern] = useState('');
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);

  const addPattern = (type: 'public' | 'internal') => {
    if (!newPattern.trim()) return;
    const key = type === 'public' ? 'publicHoistPattern' : 'hoistPattern';
    setConfig(prev => ({
      ...prev,
      install: {
        ...prev.install,
        [key]: [...prev.install[key], newPattern.trim()]
      }
    }));
    setNewPattern('');
  };

  const removePattern = (type: 'public' | 'internal', index: number) => {
    const key = type === 'public' ? 'publicHoistPattern' : 'hoistPattern';
    setConfig(prev => ({
      ...prev,
      install: {
        ...prev.install,
        [key]: prev.install[key].filter((_, i) => i !== index)
      }
    }));
  };

  const toml = useMemo(() => {
    let lines: string[] = ['# Generated by BunRegistry Hub v2.4.1 (Bun 1.3.2 Standard)'];
    
    // Runtime
    lines.push(`smol = ${config.smol}`);
    lines.push(`telemetry = ${config.telemetry}`);
    lines.push(`logLevel = "${config.logLevel}"`);
    if (config.preload.length > 0) {
      lines.push(`preload = [${config.preload.map(p => `"${p}"`).join(', ')}]`);
    }
    
    // Lockfile Version (New in 1.3.2)
    lines.push('\n# Lockfile configVersion (0=Hoisted, 1=Isolated default)');
    lines.push(`configVersion = ${config.configVersion}`);

    // Test
    lines.push('\n[test]');
    lines.push(`coverage = ${config.test.coverage}`);
    lines.push(`randomize = ${config.test.randomize}`);
    if (config.test.rerunEach > 0) lines.push(`rerunEach = ${config.test.rerunEach}`);
    if (config.test.passWithNoTests) lines.push(`passWithNoTests = true`);
    if (config.test.onlyFailures) lines.push(`onlyFailures = true`);
    
    // Install
    lines.push('\n[install]');
    lines.push(`linker = "${config.install.linker}"`);
    lines.push(`production = ${config.install.production}`);
    lines.push(`frozenLockfile = ${config.install.frozenLockfile}`);
    lines.push(`saveTextLockfile = ${config.install.saveTextLockfile}`);
    
    if (config.install.publicHoistPattern.length > 0) {
      lines.push(`publicHoistPattern = [${config.install.publicHoistPattern.map(p => `"${p}"`).join(', ')}]`);
    }
    if (config.install.hoistPattern.length > 0) {
      lines.push(`hoistPattern = [${config.install.hoistPattern.map(p => `"${p}"`).join(', ')}]`);
    }

    if (config.disableNativeLinker) {
        lines.push('\n# Environment Overrides:');
        lines.push('# BUN_FEATURE_FLAG_DISABLE_NATIVE_DEPENDENCY_LINKER=1');
    }

    return lines.join('\n');
  }, [config]);

  const cliPreview = useMemo(() => {
    let parts = ['bun'];
    if (config.cpuProf) {
        parts.push('--cpu-prof');
        parts.push(`--cpu-prof-name "${config.cpuProfName}"`);
        parts.push(`--cpu-prof-dir "${config.cpuProfDir}"`);
    }
    parts.push('index.ts');
    return parts.join(' ');
  }, [config.cpuProf, config.cpuProfName, config.cpuProfDir]);

  const copyToClipboard = async (text: string) => {
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard) {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setCopyError(false);
        setTimeout(() => setCopied(false), 2000);
      } else {
        throw new Error('Clipboard API not available');
      }
    } catch (err) {
      console.error('Failed to copy text: ', err);
      setCopyError(true);
      setTimeout(() => setCopyError(false), 3000);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="space-y-6 overflow-y-auto max-h-[850px] no-scrollbar pr-1 pb-12">
        {/* Runtime & Version Hub */}
        <div className="glass-panel p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-emerald-500/10 rounded-xl text-emerald-500">
              <Settings size={20} />
            </div>
            <div>
                <h3 className="font-black text-slate-800 dark:text-slate-100 uppercase tracking-widest text-sm">Engine Primitives</h3>
                <p className="text-[10px] text-slate-500 font-bold uppercase italic tracking-tighter">Bun v1.3.2 Feature Set</p>
            </div>
          </div>
          
          <div className="space-y-4">
            <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800">
                <div className="flex items-center justify-between mb-3">
                    <div className="flex flex-col">
                        <span className="text-xs font-black text-slate-700 dark:text-slate-200 uppercase tracking-tighter italic">Lockfile configVersion</span>
                        <span className="text-[9px] text-slate-500">v1 standardizes isolated linking for workspaces</span>
                    </div>
                    <div className="flex bg-white dark:bg-slate-950 p-1 rounded-xl border border-slate-200 dark:border-slate-800">
                        {[0, 1].map(v => (
                            <button 
                                key={v}
                                onClick={() => setConfig(prev => ({ ...prev, configVersion: v as 0|1 }))}
                                className={`px-4 py-1.5 rounded-lg text-xs font-black transition-all ${config.configVersion === v ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/20' : 'text-slate-400'}`}
                            >
                                v{v}
                            </button>
                        ))}
                    </div>
                </div>
            </div>

            <label className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 cursor-pointer hover:border-emerald-500/30 transition-all">
              <div className="flex flex-col">
                <span className="text-xs font-black text-slate-700 dark:text-slate-200 uppercase tracking-tighter">SMOL MODE</span>
                <span className="text-[10px] text-slate-500">Sacrifice throughput for memory isolation</span>
              </div>
              <input 
                type="checkbox" 
                checked={config.smol} 
                onChange={(e) => setConfig(prev => ({ ...prev, smol: e.target.checked }))}
                className="w-5 h-5 rounded-lg border-slate-300 text-emerald-600 focus:ring-emerald-500 dark:border-slate-700 dark:bg-slate-800"
              />
            </label>

            <label className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 cursor-pointer hover:border-emerald-500/30 transition-all">
              <div className="flex flex-col">
                <span className="text-xs font-black text-slate-700 dark:text-slate-200 uppercase tracking-tighter">Native Linker Logic</span>
                <span className="text-[10px] text-slate-500">Disable built-in binlinking defaults</span>
              </div>
              <input 
                type="checkbox" 
                checked={config.disableNativeLinker} 
                onChange={(e) => setConfig(prev => ({ ...prev, disableNativeLinker: e.target.checked }))}
                className="w-5 h-5 rounded-lg border-slate-300 text-emerald-600 focus:ring-emerald-500 dark:border-slate-700 dark:bg-slate-800"
              />
            </label>
          </div>
        </div>

        {/* Execution Profiler Section */}
        <div className="glass-panel p-6 rounded-3xl border border-amber-500/20 bg-amber-500/5 shadow-xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-amber-500/10 rounded-xl text-amber-500">
              <Microscope size={20} />
            </div>
            <div>
                <h3 className="font-black text-slate-800 dark:text-slate-100 uppercase tracking-widest text-sm">Execution Profiler</h3>
                <p className="text-[10px] text-slate-500 font-bold uppercase italic tracking-tighter">CLI Instrumentation Flags</p>
            </div>
          </div>
          
          <div className="space-y-4">
            <label className="flex items-center justify-between p-4 rounded-2xl bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 cursor-pointer hover:border-amber-500/30 transition-all">
              <div className="flex flex-col">
                <span className="text-xs font-black text-slate-700 dark:text-slate-200 uppercase tracking-tighter italic">Attach CPU Profiler</span>
                <span className="text-[10px] text-slate-500">Enable --cpu-prof wall-time instrumentation</span>
              </div>
              <input 
                type="checkbox" 
                checked={config.cpuProf} 
                onChange={(e) => setConfig(prev => ({ ...prev, cpuProf: e.target.checked }))}
                className="w-5 h-5 rounded-lg border-slate-300 text-amber-600 focus:ring-amber-500 dark:border-slate-700 dark:bg-slate-800"
              />
            </label>

            {config.cpuProf && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2 duration-300">
                    <div className="space-y-1.5">
                        <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Profile Name</label>
                        <input 
                            type="text"
                            value={config.cpuProfName}
                            onChange={(e) => setConfig(prev => ({ ...prev, cpuProfName: e.target.value }))}
                            className="w-full bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl px-4 py-2 text-xs font-mono focus:ring-1 focus:ring-amber-500 focus:outline-none"
                        />
                    </div>
                    <div className="space-y-1.5">
                        <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Output Dir</label>
                        <input 
                            type="text"
                            value={config.cpuProfDir}
                            onChange={(e) => setConfig(prev => ({ ...prev, cpuProfDir: e.target.value }))}
                            className="w-full bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl px-4 py-2 text-xs font-mono focus:ring-1 focus:ring-amber-500 focus:outline-none"
                        />
                    </div>
                </div>
            )}
          </div>
        </div>

        {/* Testing Suite */}
        <div className="glass-panel p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-rose-500/10 rounded-xl text-rose-500">
              <Beaker size={20} />
            </div>
            <div>
                <h3 className="font-black text-slate-800 dark:text-slate-100 uppercase tracking-widest text-sm">Test Orchestration</h3>
                <p className="text-[10px] text-slate-500 font-bold uppercase italic tracking-tighter">Module Mocking & PTY Integration</p>
            </div>
          </div>
          
          <div className="space-y-3">
            {[
                { key: 'passWithNoTests', label: 'Pass with no tests', desc: 'Exit 0 on empty test suites' },
                { key: 'onlyFailures', label: 'Suppress successes', desc: 'Strict mode log filtering' },
                { key: 'coverage', label: 'Coverage metrics', desc: 'Attaches native V8 reports' }
            ].map(item => (
                <label key={item.key} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 cursor-pointer hover:border-rose-500/30 transition-all">
                <div className="flex flex-col">
                    <span className="text-xs font-black text-slate-700 dark:text-slate-200 uppercase tracking-tighter italic">{item.label}</span>
                    <span className="text-[9px] text-slate-500 font-bold">{item.desc}</span>
                </div>
                <input 
                    type="checkbox" 
                    checked={(config.test as any)[item.key]} 
                    onChange={(e) => setConfig(prev => ({ ...prev, test: { ...prev.test, [item.key]: e.target.checked } }))}
                    className="w-5 h-5 rounded-lg border-slate-300 text-rose-600 focus:ring-rose-500 dark:border-slate-700 dark:bg-slate-800"
                />
                </label>
            ))}
          </div>
        </div>
      </div>

      {/* Output Panel */}
      <div className="space-y-6">
        <div className="glass-panel rounded-3xl border border-slate-200 dark:border-slate-800 flex flex-col h-full min-h-[600px] overflow-hidden shadow-2xl relative">
          <div className="p-5 border-b border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50 flex justify-between items-center">
            <div className="flex items-center gap-3">
              <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
              <span className="text-xs font-black text-slate-700 dark:text-slate-200 font-mono italic">Configuration Manifest</span>
            </div>
            <div className="flex items-center gap-2">
               <button 
                onClick={() => copyToClipboard(toml)}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] transition-all shadow-xl ${
                  copied 
                    ? 'bg-emerald-500 text-white shadow-emerald-500/30' 
                    : 'bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900 hover:scale-[1.02] active:scale-95'
                }`}
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? 'COPIED' : 'COPY TOML'}
              </button>
            </div>
          </div>
          
          <div className="flex-1 bg-black p-8 font-mono text-[13px] leading-relaxed overflow-y-auto selection:bg-emerald-500/40 custom-scrollbar">
            <div className="mb-8">
               <div className="flex items-center gap-2 mb-4 text-indigo-400 font-black text-[10px] uppercase tracking-widest border-b border-white/10 pb-2">
                  <TerminalIcon size={12} /> Execution Flag Preview
               </div>
               <div className="p-4 bg-slate-900/50 rounded-xl border border-white/5 text-emerald-400 break-all select-all font-mono">
                  {cliPreview}
               </div>
            </div>

            <pre className="text-slate-300">
              {toml.split('\n').map((line, i) => (
                <div key={i} className="flex gap-8 hover:bg-white/5 px-2 -mx-2 transition-colors">
                  <span className="w-6 text-slate-700 select-none text-right italic opacity-50">{i + 1}</span>
                  <span className={`
                    ${line.startsWith('#') ? 'text-slate-600 italic' : ''}
                    ${line.includes('=') ? 'text-emerald-400' : ''}
                    ${line.startsWith('[') ? 'text-indigo-400 font-black' : ''}
                    ${line.includes('configVersion') ? 'text-sky-400' : ''}
                  `}>
                    {line}
                  </span>
                </div>
              ))}
            </pre>
          </div>
          <div className="p-4 bg-slate-900 border-t border-slate-800 flex justify-between items-center px-8">
             <div className="flex items-center gap-4">
                <span className="text-[10px] font-mono text-emerald-500/70 flex items-center gap-2 uppercase tracking-widest italic">
                    <Zap size={12} className="text-amber-500"/> KQueue Sync
                </span>
                <span className="text-[10px] font-mono text-sky-500/70 flex items-center gap-2 uppercase tracking-widest italic">
                    <Cpu size={12}/> SHA-256 PARITY
                </span>
             </div>
             <span className="text-[9px] font-mono text-slate-600 uppercase tracking-widest">UTF-8 Compliance: Verified</span>
          </div>
        </div>

        <div className="p-5 rounded-3xl border border-amber-500/20 bg-amber-500/5 flex items-start gap-4 shadow-sm">
           <Info size={20} className="text-amber-500 shrink-0 mt-0.5" />
           <div className="space-y-1">
              <p className="text-xs font-black text-amber-700 dark:text-amber-400 uppercase tracking-widest italic">Runtime Insights: --cpu-prof</p>
              <p className="text-[10px] text-slate-500 leading-relaxed font-medium">
                Generate <code className="text-amber-600 font-bold">.cpuprofile</code> files natively. Open them in <span className="text-indigo-500 font-bold italic">Chrome DevTools → Performance</span> for deep wall-time analysis of edge orchestration logic.
              </p>
           </div>
        </div>
      </div>
    </div>
  );
};
