#!/usr/bin/env bun
// Configuration constants for Tension Field Analysis
// [TENSION-CONFIG-001]

export { PORT_MCP_DEFAULT } from "./constants/ports";

export const TENSION_CONSTANTS = {
  // Data management
  MAX_DATA_POINTS: 10000,
  DATA_FILE: './tension-history.json',
  
  // Analysis thresholds
  STABILITY_THRESHOLD: 0.001,
  CORRELATION_THRESHOLD: 0.7,
  HIGH_CORRELATION_THRESHOLD: 0.9,
  ANOMALY_RATE_THRESHOLD: 0.1,
  HIGH_ANOMALY_RATE_THRESHOLD: 0.2,
  
  // Risk assessment thresholds
  CRITICAL_RISK_THRESHOLD: 95,
  HIGH_RISK_THRESHOLD: 85,
  MEDIUM_RISK_THRESHOLD: 75,
  AVG_RISK_THRESHOLD: 70,
  
  // Pattern detection thresholds
  DAILY_VARIANCE_THRESHOLD: 100,
  WEEKLY_VARIANCE_THRESHOLD: 80,
  VOLATILITY_THRESHOLD: 30,
  ANOMALY_CLUSTER_THRESHOLD: 2,
  MIN_CLUSTER_LENGTH: 3,
  
  // Risk scoring
  CRITICAL_RISK_SCORE: 30,
  HIGH_RISK_SCORE: 20,
  MEDIUM_RISK_SCORE: 10,
  VERY_HIGH_ANOMALY_SCORE: 25,
  HIGH_ANOMALY_SCORE: 15,
  STRONG_TREND_SCORE: 15,
  SPORADIC_PATTERN_SCORE: 10,
  
  // Risk levels
  CRITICAL_RISK_LEVEL: 80,
  HIGH_RISK_LEVEL: 60,
  MEDIUM_RISK_LEVEL: 40,
  
  // Pattern strength normalization
  DAILY_VARIANCE_NORMALIZER: 500,
  WEEKLY_VARIANCE_NORMALIZER: 400,
  VOLATILITY_NORMALIZER: 50,
  CORRELATION_STRENGTH_FACTOR: 10,
  
  // Trend analysis
  TREND_CONFIDENCE_FACTOR: 100,
  TREND_STRENGTH_THRESHOLD: 0.7,
  RECOMMENDATION_STRENGTH_THRESHOLD: 0.8,
  
  // MCP Server configuration
  DEFAULT_MCP_PORT: 3002,
  DEFAULT_MCP_HOST: 'localhost',
  DEFAULT_DEPTH: 3,
  DEFAULT_TIME_HORIZON: 24,
  DEFAULT_TIME_RANGE: 24,
  DEFAULT_LIMIT: 50,
  NETWORK_ANALYSIS_LIMIT: 10,
  QUERY_LIMIT: 100,
  
  // Enhanced analyzer constants
  PREDICTION_MODEL_FILE: './tension-prediction-model.json',
  ANOMALY_THRESHOLD: 2.5,
  PREDICTION_HORIZON: 24,
  MAX_LAG_HOURS: 24,
  MIN_PREDICTION_DATA: 10,
  SMOOTHING_ALPHA: 0.3,
  REGIME_CHANGE_THRESHOLD: 1.5,
  REGIME_CHANGE_NORMALIZER: 3,
  STABILITY_FACTOR: 0.1,
  TREND_CHANGE_THRESHOLD: 0.1,
  HIGH_CONFIDENCE_THRESHOLD: 0.8,
  HIGH_RISK_PROBABILITY: 0.7,
  UNCERTAINTY_RISK_THRESHOLD: 0.3,
  VOLATILITY_RISK_THRESHOLD: 10,
  RISK_INCREMENT_HIGH: 0.4,
  RISK_INCREMENT_MEDIUM: 0.3,
  RISK_INCREMENT_LOW: 0.3,
  RECENT_ANOMALY_HOURS: 3600000, // 1 hour in ms
  PREDICTION_TARGET_HOURS: 3600000, // 1 hour in ms
  DEFAULT_CONFIDENCE: 0.5,
  MIN_HISTORY_POINTS: 20,
  DEFAULT_WINDOW_SIZE: 10,
  RECENT_WINDOW_SIZE: 5,
  DEFAULT_EXPORT_LIMIT: 1000,
  SEASONAL_PERIOD: 24,
  DEFAULT_HISTORY_SIZE: 50,
  DEFAULT_WEIGHT_ALPHA: 0.1,
  DEVIATION_SPIKE_THRESHOLD: 1,
  DEVIATION_GRADUAL_THRESHOLD: 0.5,
  MIN_COMPARISON_HISTORY: 10,
  KEY_NODES_LIMIT: 5,
  
  // Colors for UI (following user rules)
  COLORS: {
    ENTERPRISE: '#3b82f6',
    SUCCESS: '#22c55e',
    WARNING: '#f59e0b',
    ERROR: '#ef4444',
    BACKGROUND: '#1f2937'
  }
} as const;

export type TensionConstants = typeof TENSION_CONSTANTS;
