#!/usr/bin/env bun
import { AUTH, DEFAULT_PORT, DEFAULT_HOSTNAME, DEFAULT_TEST_PORT, DB } from '../config';

const output = `# stuff monorepo environment variables
# Generated by: bun run env:example

# Server port
STUFF_PORT=${DEFAULT_PORT}

# Server hostname
STUFF_HOSTNAME=${DEFAULT_HOSTNAME}

# Full server URL (overrides port/hostname)
STUFF_SERVER=

# SQLite database path
STUFF_DB_PATH=${DB.DEFAULT_PATH}

# Bcrypt hash for bearer token auth
${AUTH.API_TOKEN_ENV}=
`;

const dest = import.meta.dir + '/../../.env.example';
await Bun.write(dest, output);
console.log(`Wrote ${dest}`);
console.log(output);
