#!/usr/bin/env bun
/**
 * Tier-1380 OMEGA Git Hooks Installer
 * Install pre-commit hooks with governance checks
 */

import { $ } from "bun";

interface HookConfig {
	enablePreCommit: boolean;
	enablePrepareCommitMsg: boolean;
	enableCommitMsg: boolean;
	enablePostCommit: boolean;
	enablePrePush: boolean;
	autoFix: boolean;
}

const HOOK_SCRIPTS = {
	preCommit: `#!/bin/sh
# Tier-1380 OMEGA Pre-Commit Hook
# Auto-generated by install-hooks.ts

echo "Running Tier-1380 OMEGA pre-commit checks..."
bun ~/.kimi/skills/tier1380-commit-flow/scripts/pre-commit-hook.ts

exit $?
`,

	prepareCommitMsg: `#!/bin/sh
# Tier-1380 OMEGA Prepare Commit Message Hook
# Helps write proper commit messages

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

bun ~/.kimi/skills/tier1380-commit-flow/scripts/prepare-commit-msg.ts "$COMMIT_MSG_FILE" "$COMMIT_SOURCE"

exit 0
`,

	commitMsg: `#!/bin/sh
# Tier-1380 OMEGA Commit Message Hook
# Validates commit message format

COMMIT_MSG_FILE=$1
MESSAGE=$(cat "$COMMIT_MSG_FILE")

# Skip merge commits
if echo "$MESSAGE" | grep -q "^Merge"; then
    exit 0
fi

echo "Validating commit message format..."
bun ~/.kimi/skills/tier1380-commit-flow/scripts/validate-message.ts "$MESSAGE"

exit $?
`,

	postCommit: `#!/bin/sh
# Tier-1380 OMEGA Post-Commit Hook
# Records commit to history

HASH=$(git rev-parse HEAD)
MESSAGE=$(git log -1 --pretty=%B)
AUTHOR=$(git log -1 --pretty=%an)
DATE=$(git log -1 --pretty=%ad --date=iso)

echo "Recording commit to history..."
bun ~/.kimi/skills/tier1380-commit-flow/scripts/commit-history.ts record "$HASH" "$MESSAGE" "$AUTHOR" "$DATE"
`,

	prePush: `#!/bin/sh
# Tier-1380 OMEGA Pre-Push Hook
# Validates before pushing

echo "Running Tier-1380 OMEGA pre-push checks..."
bun ~/.kimi/skills/tier1380-commit-flow/scripts/pre-push-hook.ts

exit $?
`,
};

async function installHooks(config: HookConfig): Promise<void> {
	const gitDir = (await $`git rev-parse --git-dir`.text()).trim();
	const hooksDir = `${gitDir}/hooks`;

	console.log("📁 Installing hooks to:", hooksDir);
	console.log();

	// Install pre-commit hook
	if (config.enablePreCommit) {
		const hookPath = `${hooksDir}/pre-commit`;
		await Bun.write(hookPath, HOOK_SCRIPTS.preCommit);
		await $`chmod +x ${hookPath}`;
		console.log("✅ Installed: pre-commit");
	}

	// Install prepare-commit-msg hook
	if (config.enablePrepareCommitMsg) {
		const hookPath = `${hooksDir}/prepare-commit-msg`;
		await Bun.write(hookPath, HOOK_SCRIPTS.prepareCommitMsg);
		await $`chmod +x ${hookPath}`;
		console.log("✅ Installed: prepare-commit-msg");
	}

	// Install commit-msg hook
	if (config.enableCommitMsg) {
		const hookPath = `${hooksDir}/commit-msg`;
		await Bun.write(hookPath, HOOK_SCRIPTS.commitMsg);
		await $`chmod +x ${hookPath}`;
		console.log("✅ Installed: commit-msg");
	}

	// Install post-commit hook
	if (config.enablePostCommit) {
		const hookPath = `${hooksDir}/post-commit`;
		await Bun.write(hookPath, HOOK_SCRIPTS.postCommit);
		await $`chmod +x ${hookPath}`;
		console.log("✅ Installed: post-commit");
	}

	// Install pre-push hook
	if (config.enablePrePush) {
		const hookPath = `${hooksDir}/pre-push`;
		await Bun.write(hookPath, HOOK_SCRIPTS.prePush);
		await $`chmod +x ${hookPath}`;
		console.log("✅ Installed: pre-push");
	}

	console.log();
}

async function uninstallHooks(): Promise<void> {
	const gitDir = (await $`git rev-parse --git-dir`.text()).trim();
	const hooksDir = `${gitDir}/hooks`;

	const hooks = [
		"pre-commit",
		"prepare-commit-msg",
		"commit-msg",
		"post-commit",
		"pre-push",
	];

	console.log("🗑️  Uninstalling hooks...");
	console.log();

	for (const hook of hooks) {
		const hookPath = `${hooksDir}/${hook}`;
		try {
			await $`rm -f ${hookPath}`;
			console.log(`✅ Removed: ${hook}`);
		} catch {
			console.log(`⚠️  Not found: ${hook}`);
		}
	}

	console.log();
}

async function checkStatus(): Promise<void> {
	const gitDir = (await $`git rev-parse --git-dir`.text()).trim();
	const hooksDir = `${gitDir}/hooks`;

	console.log("📋 Hook Status");
	console.log();

	const hooks = [
		"pre-commit",
		"prepare-commit-msg",
		"commit-msg",
		"post-commit",
		"pre-push",
	];

	for (const hook of hooks) {
		const hookPath = `${hooksDir}/${hook}`;
		try {
			await $`test -f ${hookPath}`.quiet();
			const content = await Bun.file(hookPath).text();
			const isTier1380 = content.includes("Tier-1380 OMEGA");
			console.log(
				`${isTier1380 ? "✅" : "⚠️"} ${hook}: ${isTier1380 ? "Tier-1380" : "Custom/other"}`,
			);
		} catch {
			console.log(`❌ ${hook}: Not installed`);
		}
	}

	console.log();
}

// Main
if (import.meta.main) {
	const args = Bun.argv.slice(2);
	const command = args[0] || "install";

	console.log("╔════════════════════════════════════════════════════════╗");
	console.log("║     Tier-1380 OMEGA Git Hooks Manager                  ║");
	console.log("╚════════════════════════════════════════════════════════╝");
	console.log();

	switch (command) {
		case "install": {
			const config: HookConfig = {
				enablePreCommit: !args.includes("--no-pre-commit"),
				enablePrepareCommitMsg: !args.includes("--no-prepare-commit-msg"),
				enableCommitMsg: !args.includes("--no-commit-msg"),
				enablePostCommit: !args.includes("--no-post-commit"),
				enablePrePush: !args.includes("--no-pre-push"),
				autoFix: args.includes("--auto-fix"),
			};

			await installHooks(config);

			console.log("Configuration:");
			console.log(`  Pre-commit:         ${config.enablePreCommit ? "✅" : "❌"}`);
			console.log(
				`  Prepare-commit-msg: ${config.enablePrepareCommitMsg ? "✅" : "❌"}`,
			);
			console.log(`  Commit-msg:         ${config.enableCommitMsg ? "✅" : "❌"}`);
			console.log(`  Post-commit:        ${config.enablePostCommit ? "✅" : "❌"}`);
			console.log(`  Pre-push:           ${config.enablePrePush ? "✅" : "❌"}`);
			console.log(`  Auto-fix:           ${config.autoFix ? "✅" : "❌"}`);
			console.log();
			console.log("Hooks installed successfully!");
			break;
		}

		case "uninstall":
			await uninstallHooks();
			console.log("Hooks uninstalled.");
			break;

		case "status":
			await checkStatus();
			break;

		default:
			console.log("Usage:");
			console.log(
				"  install [--no-pre-commit] [--no-prepare-commit-msg] [--no-commit-msg] [--no-post-commit] [--no-pre-push] [--auto-fix]",
			);
			console.log("  uninstall");
			console.log("  status");
			break;
	}
}

export { installHooks, uninstallHooks, checkStatus, type HookConfig };
