# Tier-1380 OMEGA: GitHub Actions Workflow Example
# Copy to .github/workflows/matrix-cols.yml

name: 🔥 Matrix Columns CI

on:
  push:
    branches: [main, master]
    paths:
      - 'matrix/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'matrix/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run tests
        run: bun test matrix/column-standards.test.ts
      
      - name: Validate schema
        run: bun matrix/column-standards-all.ts validate
      
      - name: Generate documentation
        run: |
          bun matrix/column-standards-all.ts export matrix/COLUMN-REFERENCE.md
          bun matrix/column-standards-all.ts matrix > matrix/MATRIX-VIEW.txt
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: matrix-docs
          path: |
            matrix/COLUMN-REFERENCE.md
            matrix/MATRIX-VIEW.txt

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Check TypeScript
        run: bun tsc --noEmit matrix/column-standards-all.ts
      
      - name: Check formatting
        run: bunx @biomejs/biome check matrix/*.ts || true

  stats:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Generate stats
        run: |
          echo "## 🔥 Matrix Statistics" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          bun matrix/column-standards-all.ts stats --json | jq -r '
            "- Total Columns: \(.totalColumns)",
            "- Total Zones: \(.totalZones)",
            "",
            "### By Zone:",
            (.byZone | to_entries[] | "- \(.key): \(.value) columns"),
            "",
            "### By Owner:",
            (.byOwner | to_entries[] | "- \(.key): \(.value) columns")
          ' >> $GITHUB_STEP_SUMMARY

  publish-docs:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Generate all docs
        run: |
          mkdir -p docs/matrix
          bun matrix/column-standards-all.ts export docs/matrix/COLUMN-REFERENCE.md
          bun matrix/column-standards-all.ts stats > docs/matrix/STATS.md
          bun matrix/column-standards-all.ts shortcuts > docs/matrix/SHORTCUTS.md
          bun matrix/column-standards-all.ts flags > docs/matrix/FLAGS.md
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/matrix
