// Built-ins grouped by Bun's 1.4 "Also built in" release section.
import type { Bun14Capability } from './types.ts';
import { asReleaseCapabilityId } from '../../lib/types/branded.ts';

const RELEASE = 'https://bun.com/blog/bun-v1.4#also-built-in';

export const BUN_14_BUILTIN_CAPABILITIES: Bun14Capability[] = [
  {
    id: asReleaseCapabilityId('bun-json5-native'),
    domain: 'runtime',
    symbol: 'Bun.JSON5',
    changeKind: 'release-window',
    adoption: 'contract',
    summary: 'Provides built-in JSON5 parsing, serialization, and module loading.',
    boundary: 'Use only where JSON5 is the declared wire format; do not loosen JSON contracts.',
    releaseUrl: RELEASE,
    docsUrl: 'https://bun.com/reference/bun/JSON5',
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-bugfix-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-jsonl-native'),
    domain: 'runtime',
    symbol: 'Bun.JSONL.parse / parseChunk',
    changeKind: 'release-window',
    adoption: 'candidate',
    summary: 'Parses complete or incrementally streamed newline-delimited JSON.',
    boundary: 'Existing append-only JSONL owners keep their current validation until migrated.',
    releaseUrl: RELEASE,
    docsUrl: 'https://bun.com/reference/bun/JSONL',
    assetIds: [],
    contractFiles: [],
  },
  {
    id: asReleaseCapabilityId('bun-jsonc-native'),
    domain: 'runtime',
    symbol: 'Bun.JSONC.parse',
    changeKind: 'release-window',
    adoption: 'contract',
    summary: 'Parses JSON with comments and trailing commas using Bun’s built-in parser.',
    boundary: 'Configuration boundary only; emitted registries remain strict JSON.',
    releaseUrl: RELEASE,
    docsUrl: 'https://bun.com/reference/bun/JSONC',
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-behavior-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-toml-native'),
    domain: 'runtime',
    symbol: 'Bun.TOML.parse / stringify',
    changeKind: 'release-window',
    adoption: 'integrated',
    summary: 'Parses TOML 1.1 and exposes serialization in the stable Bun 1.4 contract.',
    boundary: 'TOML is configuration input; validated domain shapes remain separate.',
    releaseUrl: RELEASE,
    docsUrl: 'https://bun.com/docs/runtime/toml',
    assetIds: [],
    contractFiles: [
      'tests/bun-toml-version-contract.test.ts',
      'tests/config-toml-snapshot.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('bun-archive-native'),
    domain: 'runtime',
    symbol: 'Bun.Archive',
    changeKind: 'release-window',
    adoption: 'integrated',
    summary: 'Creates and extracts tar archives, including gzip-compressed release snapshots.',
    boundary: 'Archives preserve reviewed release state; they never authorize media republication.',
    releaseUrl: RELEASE,
    docsUrl: 'https://bun.com/reference/bun/Archive',
    assetIds: [],
    contractFiles: ['tests/bun-1.4-channel-release.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-ansi-layout-native'),
    domain: 'runtime',
    symbol: 'Bun.sliceAnsi / wrapAnsi',
    changeKind: 'release-window',
    adoption: 'integrated',
    summary: 'Provides ANSI- and grapheme-aware terminal slicing and wrapping.',
    boundary: 'Terminal presentation only; browser layout remains CSS-owned.',
    releaseUrl: RELEASE,
    docsUrl: 'https://bun.com/docs/runtime/utils',
    assetIds: [],
    contractFiles: ['tests/console-depth.test.ts', 'tests/regression/bun-1.3.11.test.ts'],
  },
];
