// @see https://bun.com/blog/bun-v1.3.14#no-orphans-exit-when-the-parent-process-dies — --no-orphans
// @released --no-orphans · released v1.3.14 · 2026-05-13 · https://bun.com/blog/bun-v1.3.14
// Official Bun 1.4 facts only. Repository paths below are adoption evidence, not fact sources.
import type { Bun14Capability } from './types.ts';
import { asReleaseCapabilityId } from '../../lib/types/branded.ts';
import { BUN_14_COLOR_CAPABILITIES } from './capability-catalog-color.ts';

const BLOG = 'https://bun.com/blog/bun-v1.4';

export const BUN_14_RUNTIME_CAPABILITIES: Bun14Capability[] = [
  {
    id: asReleaseCapabilityId('bun-xml-native'),
    domain: 'runtime',
    symbol: 'Bun.XML.parse / stringify',
    changeKind: 'new',
    adoption: 'integrated',
    summary: 'Parses bytes with XML-declared encoding and serializes the versioned RSS boundary.',
    boundary: 'RSS wire boundary; compact shapes are normalized once before domain use.',
    releaseUrl: `${BLOG}#bun-xml`,
    docsUrl: 'https://bun.com/docs/runtime/xml',
    assetIds: [],
    contractFiles: [
      'tests/bun-xml-native-contract.test.ts',
      'tests/rss-xml-shape-contract.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('bun-image-metadata'),
    domain: 'runtime',
    symbol: 'Bun.Image.metadata / maxPixels',
    changeKind: 'release-window',
    adoption: 'integrated',
    summary: 'Sniffs image format and dimensions from bytes with a pre-allocation pixel limit.',
    boundary: 'Bake-time inspection only; SVG remains separately validated and rights-gated.',
    releaseUrl: `${BLOG}#bun-image`,
    docsUrl: 'https://bun.com/docs/runtime/image#metadata',
    assetIds: ['bun-1.4-image-pipeline-src'],
    contractFiles: ['tests/bun-1.4-asset-validation.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-markdown-native'),
    domain: 'runtime',
    symbol: 'Bun.markdown',
    changeKind: 'release-window',
    adoption: 'integrated',
    summary: 'Renders Markdown for terminal evidence and generated summaries.',
    boundary:
      'Direct HTML is trusted-only; untrusted content uses the raw-HTML-off URL-safe wrapper.',
    releaseUrl: `${BLOG}#bun-markdown`,
    docsUrl: 'https://bun.com/docs/runtime/markdown',
    assetIds: [],
    contractFiles: [
      'tests/bun-markdown-ansi.test.ts',
      'tests/bun-1.4-cli-example.test.ts',
      'tests/markdown-safe-html.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('process-memory-pressure'),
    domain: 'observability',
    symbol: 'process.on("memoryPressure")',
    changeKind: 'new',
    adoption: 'contract',
    summary: 'Emits warning or critical pressure so caches and idle resources can be released.',
    boundary: 'Runtime signal only; the static gallery does not install process listeners.',
    releaseUrl: `${BLOG}#process-on-memorypressure`,
    assetIds: ['bun-1.4-memory-pressure'],
    contractFiles: ['tests/bun-1.4.0-observability-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-spawn-cgroup'),
    domain: 'platform',
    symbol: 'Bun.spawn({ cgroup })',
    changeKind: 'new',
    adoption: 'local-only',
    summary: 'Places Linux children in an existing cgroup before their first instruction.',
    boundary: 'Linux operator tooling only; unavailable to browser and Pages Functions code.',
    releaseUrl: `${BLOG}#bun-spawn-cgroup`,
    docsUrl: 'https://bun.com/docs/runtime/child-process',
    assetIds: ['bun-1.4-spawn-cgroup-poster', 'bun-1.4-spawn-cgroup'],
    contractFiles: [],
  },
  {
    id: asReleaseCapabilityId('bun-spawn-aborted-signal'),
    domain: 'platform',
    symbol: 'Bun.spawn / spawnSync signal',
    changeKind: 'changed',
    adoption: 'contract',
    summary:
      'An already-aborted signal throws AbortError with the signal reason and starts no child.',
    boundary: 'Subprocess launch validation; unrelated to public browser execution.',
    releaseUrl: `${BLOG}#bun-spawn`,
    docsUrl: 'https://bun.com/docs/runtime/child-process',
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-behavior-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-webview-local-qa'),
    domain: 'platform',
    symbol: 'Bun.WebView',
    changeKind: 'release-window',
    adoption: 'local-only',
    summary: 'Drives a system browser for interaction and screenshot QA.',
    boundary: 'Local visual QA only; never imported by Pages Functions or portal browser modules.',
    releaseUrl: `${BLOG}#bun-webview`,
    docsUrl: 'https://bun.com/docs/runtime/webview',
    assetIds: [],
    contractFiles: [],
  },
  ...BUN_14_COLOR_CAPABILITIES,
  {
    id: asReleaseCapabilityId('bun-terminal-local-tools'),
    domain: 'platform',
    symbol: 'Bun.Terminal',
    changeKind: 'release-window',
    adoption: 'local-only',
    summary: 'Provides a cross-platform native pseudo-terminal through Bun.spawn.',
    boundary: 'Interactive local tooling only; not a static portal or edge-runtime dependency.',
    releaseUrl: `${BLOG}#bun-terminal`,
    docsUrl: 'https://bun.com/docs/runtime/terminal',
    assetIds: [],
    contractFiles: [],
  },
  {
    id: asReleaseCapabilityId('bun-no-orphans'),
    domain: 'platform',
    symbol: '--no-orphans',
    changeKind: 'release-window',
    adoption: 'contract',
    summary: 'Exits with the original parent and recursively kills descendants on clean exit.',
    boundary: 'Local process lifecycle; configured separately from feed and portal code.',
    releaseUrl: `${BLOG}#no-orphans`,
    assetIds: ['bun-1.4-no-orphans'],
    contractFiles: ['tests/bun-1.4.0-install-behavior-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-string-width'),
    domain: 'runtime',
    symbol: 'Bun.stringWidth',
    changeKind: 'fixed',
    adoption: 'contract',
    summary: 'Measures terminal display width with corrected CJK and control-character behavior.',
    boundary: 'Terminal reports only; browser layout remains CSS-owned.',
    releaseUrl: `${BLOG}#bun-stringwidth`,
    docsUrl: 'https://bun.com/docs/runtime/utils',
    assetIds: ['bun-1.4-stringwidth-cjk'],
    contractFiles: ['tests/bun-1.4.0-bugfix-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-yaml-conformance'),
    domain: 'runtime',
    symbol: 'Bun.YAML',
    changeKind: 'compatibility',
    adoption: 'contract',
    summary: 'Adds cyclic-anchor support and passes the upstream YAML test suite claimed by Bun.',
    boundary: 'Configuration parsing; XML remains the feed wire format.',
    releaseUrl: `${BLOG}#bun-yaml-passes-402-402-of-yaml-test-suite`,
    docsUrl: 'https://bun.com/docs/runtime/yaml',
    assetIds: ['bun-1.4-yaml-cyclic-anchors'],
    contractFiles: ['tests/bun-1.4.0-bugfix-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('bun-cryptohasher-sha256'),
    domain: 'runtime',
    symbol: 'Bun.CryptoHasher',
    changeKind: 'changed',
    adoption: 'integrated',
    summary: 'Streams SHA-256 evidence and rejects odd-length hex input instead of truncating it.',
    boundary: 'Checksums cover fetched bytes; they do not establish media republishing rights.',
    releaseUrl: `${BLOG}#other-behavior-changes`,
    docsUrl: 'https://bun.com/docs/runtime/hashing',
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-behavior-contract.test.ts', 'tests/rss-fanout.test.ts'],
  },
  {
    id: asReleaseCapabilityId('native-web-streams'),
    domain: 'runtime',
    symbol: 'ReadableStream / WritableStream / TransformStream',
    changeKind: 'changed',
    adoption: 'integrated',
    summary:
      'Bun 1.4 moves Web Streams to native implementations with backpressure and cancellation semantics.',
    boundary:
      'Remote assets are consumed with bounded streaming reads before validation and hashing.',
    releaseUrl: `${BLOG}#streams-and-bodies`,
    docsUrl: 'https://bun.com/docs/runtime/streams',
    assetIds: [],
    contractFiles: ['tests/rss-image-fetch-policy.test.ts'],
  },
];
