// Official Bun 1.4 HTTP and fetch facts; application policy is described only as a boundary.
import type { Bun14Capability } from './types.ts';
import { asReleaseCapabilityId } from '../../lib/types/branded.ts';

const BLOG = 'https://bun.com/blog/bun-v1.4';
const SERVER_DOCS = 'https://bun.com/docs/runtime/http/server';
const FETCH_DOCS = 'https://bun.com/docs/runtime/networking/fetch';

export const BUN_14_NETWORK_CAPABILITIES: Bun14Capability[] = [
  {
    id: asReleaseCapabilityId('bun-serve-file-routes'),
    domain: 'server',
    symbol: 'Bun.serve routes: { dir }',
    changeKind: 'new',
    adoption: 'candidate',
    summary:
      'Serves normalized directory routes with native MIME, ETag, Last-Modified and Range handling.',
    boundary:
      'Candidate for local serving; Cloudflare Pages remains the public deployment boundary.',
    releaseUrl: `${BLOG}#serve-files-folders`,
    docsUrl: SERVER_DOCS,
    assetIds: [],
    contractFiles: [],
  },
  {
    id: asReleaseCapabilityId('bun-serve-range-preconditions'),
    domain: 'server',
    symbol: 'Bun.serve + Bun.file',
    changeKind: 'changed',
    adoption: 'integrated',
    summary:
      'File responses support 206 ranges and enforce If-Match / If-Unmodified-Since preconditions.',
    boundary: 'Local approved MP4s only; external media is probed upstream without republishing.',
    releaseUrl: `${BLOG}#range-and-conditional-requests`,
    docsUrl: SERVER_DOCS,
    assetIds: [],
    contractFiles: [
      'tests/bun-1.4.0-other-behavior-serve-fetch.test.ts',
      'tests/bun-1.4.0-web-api-contract.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('bun-serve-head-fallback'),
    domain: 'server',
    symbol: 'Bun.serve per-method routes',
    changeKind: 'changed',
    adoption: 'contract',
    summary: 'A GET method route now answers HEAD when no explicit HEAD handler exists.',
    boundary: 'Feed responses still own explicit body suppression and content-length validation.',
    releaseUrl: `${BLOG}#other-behavior-changes`,
    docsUrl: SERVER_DOCS,
    assetIds: [],
    contractFiles: [
      'tests/bun-1.4.0-other-behavior-serve-fetch.test.ts',
      'tests/rss-response.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('bun-serve-invalid-response'),
    domain: 'server',
    symbol: 'Bun.serve error()',
    changeKind: 'changed',
    adoption: 'contract',
    summary:
      'Invalid-status responses such as Response.error() route through error() instead of status 0.',
    boundary: 'Server error handling is probed independently from application response helpers.',
    releaseUrl: `${BLOG}#other-behavior-changes`,
    docsUrl: SERVER_DOCS,
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-other-behavior-serve-fetch.test.ts'],
  },
  {
    id: asReleaseCapabilityId('fetch-redirect-error-statuses'),
    domain: 'network',
    symbol: 'fetch redirect: "error"',
    changeKind: 'changed',
    adoption: 'contract',
    summary: 'Only 301, 302, 303, 307 and 308 reject as redirects; 304 resolves normally.',
    boundary: 'Hostile media fetches use an explicit manual redirect allowlist instead.',
    releaseUrl: `${BLOG}#other-behavior-changes`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: [
      'tests/bun-1.4.0-other-behavior-serve-fetch.test.ts',
      'tests/bun-1.4.0-fetch-deep-contract.test.ts',
      'tests/rss-image-fetch-policy.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('fetch-abort-settlement'),
    domain: 'network',
    symbol: 'fetch + AbortSignal',
    changeKind: 'fixed',
    adoption: 'integrated',
    summary: 'Already-aborted requests reject immediately and aborting a body errors its stream.',
    boundary: 'All upstream fetches have deadlines, byte ceilings and explicit redirect policy.',
    releaseUrl: `${BLOG}#fetch`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: [
      'tests/bun-1.4.0-fetch-deep-contract.test.ts',
      'tests/rss-image-fetch-policy.test.ts',
    ],
  },
  {
    id: asReleaseCapabilityId('fetch-request-compression'),
    domain: 'network',
    symbol: 'fetch compress',
    changeKind: 'new',
    adoption: 'candidate',
    summary: 'Buffered request bodies can be gzip, deflate, Brotli or zstd compressed by fetch.',
    boundary: 'Not used for GET/HEAD media discovery; reserve for future bounded report uploads.',
    releaseUrl: `${BLOG}#fetch-request-compression`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: [],
  },
  {
    id: asReleaseCapabilityId('fetch-body-failure-state'),
    domain: 'network',
    symbol: 'fetch Response.bodyUsed',
    changeKind: 'changed',
    adoption: 'contract',
    summary: 'A failed body read marks the body used; retries require a new fetch.',
    boundary: 'Partial or failed media bodies must never be hashed into the committed manifest.',
    releaseUrl: `${BLOG}#fetch-network-errors-are-now-typeerror-and-a-failed-body-read-sets-bodyused`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-fetch-deep-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('fetch-clone-consumption'),
    domain: 'network',
    symbol: 'Request.clone / Response.clone',
    changeKind: 'changed',
    adoption: 'contract',
    summary: 'Cloning after a body is read or its stream is locked now throws.',
    boundary:
      'Clone before splitting hash and decode work; never recover from a consumed response object.',
    releaseUrl: `${BLOG}#request-clone-and-response-clone-now-throw-once-the-body-has-been-read`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-fetch-deep-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('http-duplicate-headers'),
    domain: 'network',
    symbol: 'Headers.get / getSetCookie',
    changeKind: 'changed',
    adoption: 'contract',
    summary:
      'Duplicate fields combine with comma-space while Set-Cookie remains separately enumerable.',
    boundary: 'Asset validators read singleton headers and reject ambiguous framing metadata.',
    releaseUrl: `${BLOG}#fetch-responses-and-bun-serve-requests-now-combine-duplicate-headers-with`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: ['tests/bun-1.4.0-fetch-deep-contract.test.ts'],
  },
  {
    id: asReleaseCapabilityId('fetch-truncated-compression'),
    domain: 'network',
    symbol: 'fetch decompression',
    changeKind: 'fixed',
    adoption: 'integrated',
    summary:
      'Truncated close-delimited compressed responses reject instead of yielding partial bytes.',
    boundary: 'The media pipeline also requests identity encoding and rejects encoded responses.',
    releaseUrl: `${BLOG}#other-fetch-fixes`,
    docsUrl: FETCH_DOCS,
    assetIds: [],
    contractFiles: ['tests/rss-image-fetch-policy.test.ts'],
  },
];
