// ⚠️ AUTO-GENERATED by scripts/generate-env-dts.ts
// DO NOT EDIT MANUALLY
// Regenerated on: 2026-01-15T06:31:07.564Z
//
// Usage:
//   bun build --feature=DEBUG --feature=PREMIUM_SECRETS ./app.ts
//   bun run --feature=MOCK_API ./app.ts
//   bun test --feature=MOCK_API
//
// Type-safe feature checking:
//   if (process.env.DEBUG === "true") { ... }
//   Bun.env("PREMIUM_SECRETS") → type-checked

declare module "bun:bundle" {
  interface Registry {
    features: "ANALYTICS_TRACKING" | "API_DUOPLUS_IO_TENANT" | "AUDIT_LOGGING" | "BETA_FEATURES" | "CACHE_COMPRESSION" | "CONTENT_DISPOSITION_EXPORTS" | "DEBUG" | "DEVELOPMENT" | "DEV_DUOPLUS_IO_TENANT" | "ENTERPRISE" | "ENTERPRISE_ONLY" | "GITHUB" | "GITHUB_COM_TENANT" | "GITLAB" | "GITLAB_COM_TENANT" | "INTERNAL" | "INTERNAL_DUOPLUS_IO_TENANT" | "MOCK_API" | "PREMIUM_SECRETS" | "PRIVATE_REGISTRY" | "R2_STORAGE" | "RATE_LIMITING" | "SCOPING_MATRIX" | "VAULT_INTEGRATION" | "WEBHOOK_SIGNING";
  }
}

// Feature flag utilities
export const Features = {
  ANALYTICS_TRACKING: "ANALYTICS_TRACKING",
  API_DUOPLUS_IO_TENANT: "API_DUOPLUS_IO_TENANT",
  AUDIT_LOGGING: "AUDIT_LOGGING",
  BETA_FEATURES: "BETA_FEATURES",
  CACHE_COMPRESSION: "CACHE_COMPRESSION",
  CONTENT_DISPOSITION_EXPORTS: "CONTENT_DISPOSITION_EXPORTS",
  DEBUG: "DEBUG",
  DEVELOPMENT: "DEVELOPMENT",
  DEV_DUOPLUS_IO_TENANT: "DEV_DUOPLUS_IO_TENANT",
  ENTERPRISE: "ENTERPRISE",
  ENTERPRISE_ONLY: "ENTERPRISE_ONLY",
  GITHUB: "GITHUB",
  GITHUB_COM_TENANT: "GITHUB_COM_TENANT",
  GITLAB: "GITLAB",
  GITLAB_COM_TENANT: "GITLAB_COM_TENANT",
  INTERNAL: "INTERNAL",
  INTERNAL_DUOPLUS_IO_TENANT: "INTERNAL_DUOPLUS_IO_TENANT",
  MOCK_API: "MOCK_API",
  PREMIUM_SECRETS: "PREMIUM_SECRETS",
  PRIVATE_REGISTRY: "PRIVATE_REGISTRY",
  R2_STORAGE: "R2_STORAGE",
  RATE_LIMITING: "RATE_LIMITING",
  SCOPING_MATRIX: "SCOPING_MATRIX",
  VAULT_INTEGRATION: "VAULT_INTEGRATION",
  WEBHOOK_SIGNING: "WEBHOOK_SIGNING",
} as const;

export type FeatureFlag = typeof Features[keyof typeof Features];

// Helper function for runtime checks
export function isFeatureEnabled(feature: FeatureFlag): boolean {
  return process.env[feature] === "true";
}

// Helper for build-time feature detection
export function feature(name: FeatureFlag): boolean {
  // At runtime, check env variable; at build time, Bun checks actual flags
  return typeof process.env[name] !== "undefined";
}
