name: Enterprise Main Branch CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  enterprise-security-audit:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Enterprise Security Scan
        run: bun run bunx:security
        env:
          NODE_ENV: production

      - name: Compliance Validation
        run: bun run bunx:compliance
        env:
          NODE_ENV: production

      - name: Performance Benchmark
        run: bun run enterprise:benchmark
        env:
          NODE_ENV: production

      - name: Code Security Analysis
        run: bun run enterprise:security-scan
        env:
          NODE_ENV: production

      - name: Dependency Audit
        run: bun run enterprise:audit
        env:
          NODE_ENV: production

  enterprise-deployment:
    needs: enterprise-security-audit
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Enterprise Packages
        run: bun run enterprise:build-prod
        env:
          NODE_ENV: production

      - name: Run Enterprise Tests
        run: bun run enterprise:test-prod
        env:
          NODE_ENV: production

      - name: Deploy to Enterprise Registry
        run: bun run enterprise:publish-prod
        env:
          NODE_ENV: production
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          FIRE22_REGISTRY_TOKEN: ${{ secrets.FIRE22_REGISTRY_TOKEN }}

      - name: Update Enterprise Dashboard
        run: bun run enterprise:update-dashboard
        env:
          DASHBOARD_API_KEY: ${{ secrets.DASHBOARD_API_KEY }}

  enterprise-monitoring:
    needs: enterprise-deployment
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Performance Monitoring
        run: bun run enterprise:monitor-prod
        env:
          MONITORING_API_KEY: ${{ secrets.MONITORING_API_KEY }}

      - name: Compliance Reporting
        run: bun run enterprise:compliance-report
        env:
          COMPLIANCE_API_KEY: ${{ secrets.COMPLIANCE_API_KEY }}

      - name: Security Alert Setup
        run: bun run enterprise:security-alerts
        env:
          SECURITY_SLACK_WEBHOOK: ${{ secrets.SECURITY_SLACK_WEBHOOK }}
