#!/bin/bash
# 🏭 FactoryWager Tier-1380 Deployment Script
# 
# Complete deployment automation for the enhanced Tier-1380 system
# with configuration management, validation, and environment setup

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_MANAGER="$PROJECT_ROOT/tier1380-config-manager.ts"
CONFIG_FILE="$PROJECT_ROOT/config/tier1380-config.json"

# Logging functions
log() {
    local level=$1
    local message=$2
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    
    case $level in
        "INFO")
            echo -e "${BLUE}ℹ${NC} $message"
            ;;
        "SUCCESS")
            echo -e "${GREEN}✅${NC} $message"
            ;;
        "WARNING")
            echo -e "${YELLOW}⚠️${NC} $message"
            ;;
        "ERROR")
            echo -e "${RED}❌${NC} $message"
            ;;
        "SECTION")
            echo -e "\n${CYAN}$message${NC}"
            ;;
    esac
    
    echo "[$timestamp] [$level] $message" >> "$PROJECT_ROOT/logs/deployment.log" 2>/dev/null || true
}

# Check prerequisites
check_prerequisites() {
    log "SECTION" "🔍 Checking Prerequisites"
    
    # Check if Bun is installed
    if ! command -v bun &> /dev/null; then
        log "ERROR" "Bun is not installed or not in PATH"
        exit 1
    fi
    
    # Check if configuration manager exists
    if [ ! -f "$CONFIG_MANAGER" ]; then
        log "ERROR" "Configuration manager not found at $CONFIG_MANAGER"
        exit 1
    fi
    
    # Check if we're in a git repository
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        log "WARNING" "Not in a git repository"
    fi
    
    # Create logs directory
    mkdir -p "$PROJECT_ROOT/logs"
    
    log "SUCCESS" "Prerequisites check passed"
}

# Load and validate configuration
load_configuration() {
    log "SECTION" "📋 Loading Configuration"
    
    # Load from environment
    log "INFO" "Loading configuration from environment variables..."
    cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" load 2>/dev/null || true
    
    # Validate configuration
    log "INFO" "Validating configuration..."
    local validation_output=$(cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" validate)
    
    if [[ $validation_output == *"FAILED"* ]]; then
        log "ERROR" "Configuration validation failed"
        echo "$validation_output"
        exit 1
    fi
    
    log "SUCCESS" "Configuration loaded and validated"
}

# Display configuration summary
show_configuration() {
    log "SECTION" "📊 Configuration Summary"
    cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" summary
}

# Generate environment files
generate_environment_files() {
    log "SECTION" "🔧 Generating Environment Files"
    
    # Generate .env file
    local env_file="$PROJECT_ROOT/.env.tier1380"
    cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" export > "$env_file"
    
    log "SUCCESS" "Environment file generated: $env_file"
    
    # Generate Cloudflare Workers environment
    local wrangler_env="$PROJECT_ROOT/wrangler.toml.env"
    cat > "$wrangler_env" << EOF
# Cloudflare Workers Environment Variables
# Generated by Tier-1380 Deployment Script

[env.production.vars]
R2_BUCKET = "scanner-cookies"
PUBLIC_API_URL = "https://api.tier1380.com"
TIER1380_VARIANT = "enhanced-live"
TIER1380_CACHE_ENABLED = "true"
TIER1380_CACHE_TTL = "300000"
TIER1380_COMPRESSION_LEVEL = "3"
NODE_ENV = "production"

[env.staging.vars]
R2_BUCKET = "scanner-cookies-staging"
PUBLIC_API_URL = "https://staging-api.tier1380.com"
TIER1380_VARIANT = "enhanced-staging"
TIER1380_CACHE_ENABLED = "true"
TIER1380_CACHE_TTL = "120000"
TIER1380_COMPRESSION_LEVEL = "2"
NODE_ENV = "staging"
EOF
    
    log "SUCCESS" "Cloudflare Workers environment generated: $wrangler_env"
}

# Run tests
run_tests() {
    log "SECTION" "🧪 Running Tests"
    
    # Test configuration manager
    log "INFO" "Testing configuration manager..."
    cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" validate
    
    # Test enhanced citadel (if available)
    if [ -f "$PROJECT_ROOT/tier1380-enhanced-citadel.ts" ]; then
        log "INFO" "Testing enhanced citadel..."
        cd "$PROJECT_ROOT" && bun -e '
import { Tier1380EnhancedCitadel } from "./tier1380-enhanced-citadel.ts";
const citadel = new Tier1380EnhancedCitadel();
const status = await citadel.generateStatusReport();
console.log("✅ Enhanced citadel test passed");
console.log("Health:", status.health);
'
    fi
    
    log "SUCCESS" "All tests passed"
}

# Deploy to Cloudflare Workers
deploy_workers() {
    log "SECTION" "🚀 Deploying to Cloudflare Workers"
    
    # Check if wrangler is installed
    if ! command -v wrangler &> /dev/null; then
        log "WARNING" "Wrangler CLI not found. Skipping deployment."
        log "INFO" "Install wrangler with: npm install -g wrangler"
        return
    fi
    
    # Deploy to staging first
    log "INFO" "Deploying to staging..."
    if wrangler deploy --env staging; then
        log "SUCCESS" "Staging deployment successful"
    else
        log "ERROR" "Staging deployment failed"
        exit 1
    fi
    
    # Ask for production deployment
    if [ "$1" = "--production" ] || [ "$1" = "-p" ]; then
        read -p "Deploy to production? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            log "INFO" "Deploying to production..."
            if wrangler deploy --env production; then
                log "SUCCESS" "Production deployment successful"
            else
                log "ERROR" "Production deployment failed"
                exit 1
            fi
        else
            log "INFO" "Production deployment skipped"
        fi
    else
        log "INFO" "Use --production or -p to deploy to production"
    fi
}

# Verify deployment
verify_deployment() {
    log "SECTION" "🔍 Verifying Deployment"
    
    # Get worker URL from wrangler
    local worker_url=$(wrangler whoami 2>/dev/null | grep -o 'https://[^[:space:]]*\.workers\.dev' | head -1)
    
    if [ -n "$worker_url" ]; then
        log "INFO" "Testing worker at: $worker_url"
        
        # Test health endpoint
        local health_response=$(curl -s -w "%{http_code}" "$worker_url/health")
        local http_code="${health_response: -3}"
        
        if [ "$http_code" = "200" ]; then
            log "SUCCESS" "Health check passed"
        else
            log "WARNING" "Health check failed with HTTP $http_code"
        fi
        
        # Test cache stats endpoint
        local cache_response=$(curl -s -w "%{http_code}" "$worker_url/cache-stats")
        local cache_code="${cache_response: -3}"
        
        if [ "$cache_code" = "200" ]; then
            log "SUCCESS" "Cache stats endpoint working"
        else
            log "WARNING" "Cache stats endpoint failed with HTTP $cache_code"
        fi
    else
        log "WARNING" "Could not determine worker URL"
    fi
}

# Generate deployment report
generate_report() {
    log "SECTION" "📋 Generating Deployment Report"
    
    local report_file="$PROJECT_ROOT/logs/deployment_report_$(date +%Y%m%d_%H%M%S).md"
    
    cat > "$report_file" << EOF
# FactoryWager Tier-1380 Deployment Report

**Generated:** $(date)
**Environment:** ${NODE_ENV:-development}

## Configuration Summary

\`\`\`
$(cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" summary)
\`\`\`

## Deployment Steps Completed

1. ✅ Prerequisites check
2. ✅ Configuration loading and validation
3. ✅ Environment file generation
4. ✅ Test execution
5. ✅ Worker deployment
6. ✅ Deployment verification

## Environment Variables

\`\`\`bash
$(cd "$PROJECT_ROOT" && bun "$CONFIG_MANAGER" export)
\`\`\`

## Next Steps

1. Monitor the deployed worker
2. Check A/B test results
3. Verify cache performance
4. Monitor R2 storage usage
5. Set up alerts and monitoring

## Rollback Plan

If issues arise:
1. Use previous wrangler deployment
2. Restore configuration from git
3. Clear cache with POST /clear-cache
4. Monitor system health

## Support

- Configuration: \`bun tier1380-config-manager.ts\`
- Logs: \`$PROJECT_ROOT/logs/deployment.log\`
- Health: \`/health\` endpoint
- Cache: \`/cache-stats\` endpoint
EOF

    log "SUCCESS" "Deployment report generated: $report_file"
}

# Main deployment function
main() {
    local command=${1:-"help"}
    
    case $command in
        "check")
            check_prerequisites
            ;;
        "config")
            load_configuration
            show_configuration
            ;;
        "test")
            run_tests
            ;;
        "deploy")
            check_prerequisites
            load_configuration
            generate_environment_files
            run_tests
            deploy_workers "$2"
            verify_deployment
            generate_report
            ;;
        "full")
            check_prerequisites
            load_configuration
            show_configuration
            generate_environment_files
            run_tests
            deploy_workers "$2"
            verify_deployment
            generate_report
            ;;
        "help"|*)
            echo "Usage: $0 [COMMAND] [OPTIONS]"
            echo ""
            echo "Commands:"
            echo "  check           Check prerequisites"
            echo "  config          Load and display configuration"
            echo "  test            Run tests"
            echo "  deploy [opts]   Deploy to Cloudflare Workers"
            echo "  full [opts]     Full deployment pipeline"
            echo ""
            echo "Options:"
            echo "  --production, -p  Deploy to production (after staging)"
            echo ""
            echo "Examples:"
            echo "  $0 check"
            echo "  $0 config"
            echo "  $0 deploy"
            echo "  $0 deploy --production"
            echo "  $0 full --production"
            ;;
    esac
}

# Run main function with all arguments
main "$@"
