[install.scopes]
"@factorywager" = { url = "https://registry.factory-wager.com/api/npm" }

[install]
exact = true
registry = "https://registry.npmjs.org"

[publish]
registry = "https://registry.npmjs.org"
