// @see https://bun.com/docs/runtime/networking/dns#dns-prefetch — Bun.dns
// dns-prefetch.ts — auto-generated by scan.ts --fix-dns
// These domains are explicitly prefetched at runtime by Bun for lower latency
// Re-run: bun run ../scanner/scan.ts --fix-dns

import { dns } from "bun";

dns.prefetch("registry.npmjs.org", 443);
