/**
 * Render AuditFinding / AuditConcept → repo-local markdown (not bun.com).
 */
import type { AuditEntryId } from '../types/branded.ts';
import type { AuditConcept } from './audit-concept.ts';
import type { AuditFinding } from './audit-finding.ts';
import { auditConceptDocsPath, auditFindingDocsPath } from './audit-refs.ts';

function relatedMarkdown(
  related: readonly AuditEntryId[] | undefined,
  from: 'finding' | 'concept'
): string {
  if (!related?.length) return '_none_';
  return related
    .map(r => {
      const id = String(r);
      const looksLikeFinding = id.startsWith('sample-fiber') || /-\d{4}-\d{2}-\d{2}$/.test(id);
      if (looksLikeFinding) {
        const rel = from === 'concept' ? `../findings/${id}.md` : `./${id}.md`;
        return `- [\`${id}\`](${rel})`;
      }
      // Default: AuditConcept id
      const rel = from === 'finding' ? `../concepts/${id}.md` : `./${id}.md`;
      return `- [\`${id}\`](${rel})`;
    })
    .join('\n');
}

/** Stable markdown body for a finding page. */
export function renderAuditFindingMarkdown(f: AuditFinding): string {
  const since = f.since ?? '_unknown_';
  const discoveredIn = f.discoveredIn ?? since;
  const mitigatedIn = f.mitigatedIn ?? '_n/a_';
  const emitter = f.meta?.emitter ?? '_unknown_';
  const buildPin = f.meta?.buildPin ?? '_unknown_';
  const relatedDocs =
    f.relatedDocs && f.relatedDocs.length > 0
      ? f.relatedDocs.map(d => `- \`${d}\``).join('\n')
      : '_none_';
  return `# ${f.title}

> FactoryWager **AuditFinding** — sibling SSOT (not BunToken / bun.com).

| Field | Value |
|-------|-------|
| id | \`${f.id}\` |
| kind | \`${f.kind}\` |
| status | \`${f.status}\` |
| publishedAt | ${f.publishedAt} |
| since | ${since} |
| discoveredIn | ${discoveredIn} |
| mitigatedIn | ${mitigatedIn} |
| docs | [\`${auditFindingDocsPath(f.id)}\`](./${f.id}.md) |

## Description

${f.description}

## Evidence

| Field | Value |
|-------|-------|
| path | [\`${f.evidence.path}\`](../../../${f.evidence.path}) |
| algorithm | \`${f.evidence.algorithm}\` |
| digest | \`${f.evidence.digest}\` |
| sha256 companion | ${f.evidence.sha256 ? `\`${f.evidence.sha256}\`` : '_none_'} |
| mediaType | \`${f.evidence.mediaType}\` |

Verify:

\`\`\`bash
bun tools/audit-catalog.ts verify
\`\`\`

## Related (audit SSOT)

${relatedMarkdown(f.related, 'finding')}

## Related docs (BunToken / curated — opaque)

${relatedDocs}

## Meta

- emitter: \`${emitter}\`
- buildPin: \`${buildPin}\`

## Suggest

\`\`\`bash
bun tools/bun-doc-refs.ts suggest --audit "${f.id}"
bun tools/bun-doc-refs.ts suggest --audit --json "${f.id}"
bun tools/bun-doc-refs.ts suggest "Nagata map"
\`\`\`
`;
}

/** Stable markdown body for a concept page. */
export function renderAuditConceptMarkdown(c: AuditConcept): string {
  const since = c.since ?? '_unknown_';
  const refs =
    c.references && c.references.length > 0 ? c.references.map(r => `- ${r}`).join('\n') : '_none_';
  const relatedDocs =
    c.relatedDocs && c.relatedDocs.length > 0
      ? c.relatedDocs.map(d => `- \`${d}\``).join('\n')
      : '_none_';
  return `# ${c.title}

> FactoryWager **AuditConcept** — sibling SSOT (not BunToken / bun.com).

| Field | Value |
|-------|-------|
| id | \`${c.id}\` |
| kind | \`${c.kind}\` |
| publishedAt | ${c.publishedAt} |
| since | ${since} |
| docs | [\`${auditConceptDocsPath(c.id)}\`](./${c.id}.md) |

## Description

${c.description}

## References

${refs}

## Related (audit SSOT)

${relatedMarkdown(c.related, 'concept')}

## Related docs (BunToken / curated — opaque)

${relatedDocs}

## Suggest

\`\`\`bash
bun tools/bun-doc-refs.ts suggest "${c.title}"
bun tools/bun-doc-refs.ts suggest --audit "${c.id}"
bun tools/bun-doc-refs.ts suggest --audit --json "${c.id}"
\`\`\`
`;
}

/** Index page listing all findings. */
export function renderAuditFindingsIndex(findings: AuditFinding[]): string {
  const rows = findings
    .map(
      f => `| [\`${f.id}\`](./${f.id}.md) | \`${f.status}\` | ${f.title.replace(/\|/g, '\\|')} |`
    )
    .join('\n');
  return `# Audit findings index

Generated by \`bun tools/audit-catalog.ts build\`. Do not hand-edit.

| id | status | title |
|----|--------|-------|
${rows || '| _(empty)_ | | |'}

Concepts: [../concepts/](../concepts/) · [../README.md](../README.md)
`;
}

/** Index page listing all concepts. */
export function renderAuditConceptsIndex(concepts: AuditConcept[]): string {
  const rows = concepts
    .map(c => `| [\`${c.id}\`](./${c.id}.md) | ${c.title.replace(/\|/g, '\\|')} |`)
    .join('\n');
  return `# Audit concepts index

Generated by \`bun tools/audit-catalog.ts build\`. Do not hand-edit.

| id | title |
|----|-------|
${rows || '| _(empty)_ | |'}

Findings: [../findings/](../findings/) · [../README.md](../README.md)
`;
}
