/**
 * §Pattern:130 - LSP Matrix Integration
 * @pattern Pattern:130
 * @perf <50ms indexing
 * @roi ∞ (IDE autocomplete)
 * @section §IDE
 */

import { PatternMatrix, type PatternRow } from './pattern-matrix';
import type { LSPPatternInfo } from '../src/types/pattern-definitions';

export class PatternMatrixLSP {
  /**
   * Get pattern info for IDE hover
   */
  static getPatternInfo(id: string): string | null {
    const matrix = PatternMatrix.getInstance();
    const row = matrix.getRows().find((r: PatternRow) => r.section === id);
    if (!row) return null;
    
    return this.formatHoverInfo(row);
  }

  /**
   * Get autocomplete suggestions for pattern IDs
   */
  static getAutocompleteSuggestions(prefix: string): string[] {
    const matrix = PatternMatrix.getInstance();
    const rows = matrix.getRows();
    return rows
      .filter((r: PatternRow) => r.section.startsWith(prefix))
      .map((r: PatternRow) => r.section)
      .slice(0, 10); 
  }

  /**
   * Generate TypeScript definitions file for IDE
   */
  static generatePatternTypes(): string {
    const matrix = PatternMatrix.getInstance();
    const rows = matrix.getRows();
    
    let output = `// Auto-generated by Empire Pro Pattern Matrix\n`;
    output += `// Generated: ${new Date().toISOString()}\n\n`;
    
    // Export pattern IDs as const
    output += `export const PATTERN_IDS = {\n`;
    rows.forEach((row: PatternRow) => {
      const safeName = row.name.replace(/[^a-zA-Z0-9]/g, '');
      output += `  /** ${row.name} - ${row.perf} - ROI: ${row.roi} */\n`;
      output += `  ${safeName}: '${row.section}',\n`;
    });
    output += `} as const;\n\n`;
    
    // Export pattern info map
    output += `export const PATTERN_INFO: Record<string, any> = {\n`;
    rows.forEach((row: PatternRow) => {
      output += `  '${row.section}': {\n`;
      output += `    name: '${row.name}',\n`;
      output += `    category: '${row.category}',\n`;
      output += `    perf: '${row.perf}',\n`;
      output += `    roi: '${row.roi}',\n`;
      output += `    semantics: [${row.semantics.map((s: string) => `'${s}'`).join(', ')}],\n`;
      output += `  },\n`;
    });
    output += `};\n`;
    
    return output;
  }

  private static formatHoverInfo(row: PatternRow): string {
    return `
**Empire Pro Pattern: ${row.name}**
- ID: ${row.section}
- Category: ${row.category}
- Performance: ${row.perf}
- ROI: ${row.roi}
- Semantics: ${row.semantics.join(', ')}
- Dependencies: ${row.deps?.join(', ') || 'none'}

Example:
\`\`\`typescript
// Pattern ${row.section} is registered in the Master Matrix.
// Verified: ${row.verified}
\`\`\`
    `.trim();
  }
}
