#!/usr/bin/env bun
/**
 * [TEAM.CODEOWNERS.SYNC.RG:IMPLEMENTATION] Team CODEOWNERS Synchronization
 * @fileoverview Synchronize CODEOWNERS file with TEAM.md structure
 * @description Provides interfaces and utilities for mapping team structure to CODEOWNERS format
 * @module integrations/team-codeowners-sync
 *
 * [[TECH][MODULE][INSTANCE][META:{blueprint=BP-TEAM-CODEOWNERS-SYNC@2.0.0;instance-id=TEAM-CODEOWNERS-SYNC-001;version=2.0.0}]
 * [PROPERTIES:{integration={value:"team-codeowners-sync";@root:"24.3.1.0.0.0.0";@chain:["BP-HUMAN-CAPITAL","BP-CI-CD"];@version:"2.0.0"}}]]
 * [CLASS:TeamCodeownersSync][#REF:v-2.0.0.BP.TEAM.CODEOwners.SYNC.1.0.A.1.1.INTEGRATION.1.1]]
 *
 * @see {@link .github/TEAM.md} - Team structure source
 * @see {@link .github/CODEOWNERS} - Generated CODEOWNERS file
 * @see {@link scripts/generate-codeowners.ts} - CODEOWNERS generator script
 * @see {@link docs/24.0.0.0.0.0.0-HUMAN-CAPITAL-ORCHESTRATION.md} - Subsystem documentation
 */

/**
 * [TEAM.CODEOWNERS.MAPPING.RG:INTERFACE] Team to CODEOWNERS Mapping Interface
 * Interface for mapping team structure to CODEOWNERS format
 */
export interface TeamCodeownersMapping {
	/**
	 * Department identifier (e.g., "API_ROUTES", "ARBITRAGE_TRADING")
	 */
	department: string;

	/**
	 * Department lead GitHub username
	 */
	lead: string;

	/**
	 * Array of maintainer GitHub usernames
	 */
	maintainers: string[];

	/**
	 * Code paths owned by this department
	 * Format: ["src/api/*", "src/routes.ts", etc.]
	 */
	paths: string[];

	/**
	 * RG marker reference for this department
	 * Format: "TEAM.DEPARTMENT.API.ROUTES.RG"
	 */
	rgMarker?: string;

	/**
	 * Optional contact information
	 */
	contacts?: string[];
}

// [TEAM.CODEOWNERS.MAPPING.RESULT.RG:INTERFACE] Mapping Result Interface
/**
 * Result of CODEOWNERS mapping generation
 */
export interface CodeownersMappingResult {
	/**
	 * Array of department mappings
	 */
	mappings: TeamCodeownersMapping[];

	/**
	 * Total number of paths mapped
	 */
	totalPaths: number;

	/**
	 * Total number of owners (leads + maintainers)
	 */
	totalOwners: number;

	/**
	 * Generated CODEOWNERS file content
	 */
	codeownersContent: string;

	/**
	 * Metadata about the generation
	 */
	metadata: {
		generatedAt: string;
		sourceFile: string;
		departmentsCount: number;
	};
}

// [TEAM.CODEOWNERS.SYNC.UTILS.RG:IMPLEMENTATION] Synchronization Utilities
/**
 * Normalize a code path for CODEOWNERS format
 */
export function normalizeCodeownersPath(path: string): string {
	// Remove leading ./
	let normalized = path.replace(/^\.\//, '').trim();
	
	// If it's a directory path, ensure it ends with /*
	if (normalized.includes('/') && !normalized.includes('.')) {
		normalized = normalized.endsWith('/') ? `${normalized}*` : `${normalized}/*`;
	}
	
	return normalized;
}

/**
 * Generate CODEOWNERS line from mapping
 */
export function generateCodeownersLine(mapping: TeamCodeownersMapping): string[] {
	const lines: string[] = [];
	
	if (mapping.paths.length === 0 || !mapping.lead) {
		return lines;
	}

	// Add comment with department name
	const deptName = mapping.department.replace(/_/g, ' ').toUpperCase();
	lines.push(`# ${deptName} Department`);
	
	if (mapping.rgMarker) {
		lines.push(`# RG Marker: [${mapping.rgMarker}]`);
	}
	
	// Build owner list
	const owners = [mapping.lead, ...mapping.maintainers].filter(Boolean);
	const ownerList = owners.map(o => `@${o}`).join(' ');
	
	// Normalize and deduplicate paths
	const normalizedPaths = new Set<string>();
	for (const path of mapping.paths) {
		normalizedPaths.add(normalizeCodeownersPath(path));
	}
	
	// Add ownership for each normalized path
	for (const path of Array.from(normalizedPaths).sort()) {
		lines.push(`${path} ${ownerList}`);
	}
	
	return lines;
}

/**
 * Generate full CODEOWNERS content from mappings
 */
export function generateCodeownersContent(mappings: TeamCodeownersMapping[]): string {
	const lines: string[] = [
		'# CODEOWNERS file generated from .github/TEAM.md',
		'# Auto-generated by integrations/team-codeowners-sync.ts',
		'# DO NOT EDIT MANUALLY - Regenerate with: bun run scripts/generate-codeowners.ts',
		'',
		'# [CODEOWNERS.GENERATED.RG:CONFIG] Generated CODEOWNERS',
		'',
	];

	// Generate lines for each department
	for (const mapping of mappings) {
		const mappingLines = generateCodeownersLine(mapping);
		if (mappingLines.length > 0) {
			lines.push(...mappingLines);
			lines.push('');
		}
	}

	// Add fallback maintainers
	lines.push('# Fallback: All maintainers');
	lines.push('* @maintainers');
	lines.push('');

	return lines.join('\n');
}
