// CSS Module type declaration
declare const styles: {
  'lsp-dashboard': string;
  'header': string;
  'status-bar': string;
  'file-status': string;
  'lsp-status': string;
  'connected': string;
  'disconnected': string;
  'main-content': string;
  'code-editor': string;
  'editor-header': string;
  'editor-controls': string;
  'editor-container': string;
  'side-panel': string;
  'diagnostics-panel': string;
  'diagnostics-summary': string;
  'error-count': string;
  'warning-count': string;
  'info-count': string;
  'diagnostics-list': string;
  'diagnostic-item': string;
  'diagnostic-header': string;
  'severity': string;
  'line-number': string;
  'source': string;
  'message': string;
  'actions': string;
  'quick-fix': string;
  'show-help': string;
  'performance-panel': string;
  'metrics-grid': string;
  'metric-item': string;
  'metric-icon': string;
  'metric-details': string;
  'metric-label': string;
  'metric-value': string;
  'footer': string;
  'quick-actions': string;
  'btn': string;
  'no-diagnostics': string;
  'error-state': string;
  'error-icon': string;
  'error-message': string;
  'retry-btn': string;
  'error': string;
  'warning': string;
  'info': string;
  'hint': string;
};

export default styles;
