/**
 * Tier-1380 OMEGA: Tension Column Standards (31-45)
 *
 * Tension Anomaly Zone - XGBoost-powered anomaly detection
 *
 * @module column-standards-tension
 * @tier 1380-OMEGA
 */

export const TENSION_COLUMNS = {
	31: {
		name: "tension-anomaly-score",
		type: "float",
		range: [0, 1],
		owner: "tension",
		color: "🟠",
		description: "XGBoost final anomaly probability",
		precision: 4,
		required: true,
		alert: ">= 0.85",
	},
	32: {
		name: "volume-delta-q3",
		type: "integer",
		owner: "tension",
		color: "🟠",
		unit: "bets",
		description: "Q3 betting volume delta from baseline",
		required: false,
	},
	33: {
		name: "volume-ratio-main-halftime",
		type: "float",
		owner: "tension",
		color: "🟠",
		description: "Ratio of main market volume to halftime",
		range: [0, 10],
		required: false,
	},
	34: {
		name: "inertia-halftime",
		type: "float",
		owner: "tension",
		color: "🟠",
		formula: "1 - volume-ratio-main-halftime",
		description: "Halftime market inertia (1 - ratio)",
		range: [-9, 1],
		required: false,
	},
	35: {
		name: "overreact-flag-q3",
		type: "boolean",
		owner: "tension",
		color: "🟠",
		trigger: "score > 0.90 && delta > 3000",
		description: "Q3 overreaction detected",
		required: false,
	},
	36: {
		name: "underreact-flag-halftime",
		type: "boolean",
		owner: "tension",
		color: "🟠",
		trigger: "inertia > 0.5 && score > 0.70",
		description: "Halftime underreaction detected",
		required: false,
	},
	37: {
		name: "teaser-arb-opportunity-pct",
		type: "percent",
		owner: "tension",
		color: "🟠",
		precision: 1,
		description: "Teaser arbitrage opportunity percentage",
		range: [0, 100],
		required: false,
	},
	38: {
		name: "xgboost-feature-importance",
		type: "json",
		owner: "tension",
		color: "🟠",
		description: "Top 5 XGBoost feature importances",
		example: '{"volume_delta": 0.34, "inertia": 0.28, ...}',
		required: false,
	},
	39: {
		name: "model-confidence",
		type: "float",
		owner: "tension",
		color: "🟠",
		range: [0, 1],
		description: "Model prediction confidence",
		required: false,
	},
	40: {
		name: "prediction-horizon-minutes",
		type: "integer",
		owner: "tension",
		color: "🟠",
		description: "Minutes ahead for prediction",
		values: [5, 10, 15, 30, 60],
		required: false,
	},
	41: {
		name: "feature-vector-hash",
		type: "hex",
		owner: "tension",
		color: "🟠",
		description: "SHA-256 hash of input features",
		format: "0x...",
		required: false,
	},
	42: {
		name: "anomaly-type-primary",
		type: "enum",
		owner: "tension",
		color: "🟠",
		values: ["HALFTIME_UNDERREACT", "Q3_OVERREACT", "TEASER_ARBITRAGE", "BALANCED"],
		description: "Primary anomaly classification",
		required: false,
	},
	43: {
		name: "anomaly-severity",
		type: "enum",
		owner: "tension",
		color: "🟠",
		values: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
		description: "Severity level of detected anomaly",
		required: true,
	},
	44: {
		name: "related-markets-count",
		type: "integer",
		owner: "tension",
		color: "🟠",
		description: "Number of related markets showing similar patterns",
		required: false,
	},
	45: {
		name: "tension-profile-link",
		type: "url",
		owner: "tension",
		color: "🟠",
		protocol: "https",
		pattern: "profiles.factory-wager.com/tension/{timestamp}_{id}.md",
		description: "Deep link to tension analysis profile",
		required: false,
	},
} as const;

export type TensionColumnIndex = keyof typeof TENSION_COLUMNS;
export type TensionColumnName = (typeof TENSION_COLUMNS)[TensionColumnIndex]["name"];
