#!/usr/bin/env bun
/**
 * 🔥 Matrix View v1.3.8
 * Bun test CLI options matrix (6-column view)
 *
 * @module matrix/matrix-view
 * @tier 1380-OMEGA
 * @version 1.3.8
 */

export interface CLIOption {
	Name: string;
	Pattern: string;
	Version: string;
	Topic: string;
	Type: "boolean" | "string" | "number" | "string[]" | "enum";
	Example: string;
}

/**
 * Bun test CLI options matrix
 * 6-column view: Name, Pattern, Version, Topic, Type, Example
 */
export const cliOptionsTable: CLIOption[] = [
	// Execution
	{
		Name: "--watch",
		Pattern: "--watch",
		Version: "1.0.0",
		Topic: "execution",
		Type: "boolean",
		Example: "bun test --watch",
	},
	{
		Name: "--watchPath",
		Pattern: "--watchPath=<paths>",
		Version: "1.3.0",
		Topic: "execution",
		Type: "string[]",
		Example: "bun test --watchPath=src --watchPath=tests",
	},
	{
		Name: "--watchAll",
		Pattern: "--watchAll",
		Version: "1.0.0",
		Topic: "execution",
		Type: "boolean",
		Example: "bun test --watchAll",
	},
	{
		Name: "--bail",
		Pattern: "--bail[=count]",
		Version: "1.0.0",
		Topic: "execution",
		Type: "number",
		Example: "bun test --bail=5",
	},
	{
		Name: "--testNamePattern",
		Pattern: "--testNamePattern=<regex>",
		Version: "1.0.0",
		Topic: "filtering",
		Type: "string",
		Example: "bun test --testNamePattern='math'",
	},
	{
		Name: "--testPathPattern",
		Pattern: "--testPathPattern=<regex>",
		Version: "1.0.0",
		Topic: "filtering",
		Type: "string",
		Example: "bun test --testPathPattern='unit'",
	},
	{
		Name: "--grep",
		Pattern: "-t, --grep=<pattern>",
		Version: "1.3.7",
		Topic: "filtering",
		Type: "string",
		Example: "bun test -t 'should add'",
	},
	{
		Name: "--coverage",
		Pattern: "--coverage",
		Version: "1.0.0",
		Topic: "coverage",
		Type: "boolean",
		Example: "bun test --coverage",
	},
	{
		Name: "--coverageDirectory",
		Pattern: "--coverageDirectory=<path>",
		Version: "1.0.0",
		Topic: "coverage",
		Type: "string",
		Example: "bun test --coverageDirectory=./coverage",
	},
	{
		Name: "--coverageReporters",
		Pattern: "--coverageReporters=<reporters>",
		Version: "1.0.0",
		Topic: "coverage",
		Type: "string[]",
		Example: "bun test --coverageReporters=text --coverageReporters=html",
	},
	{
		Name: "--ci",
		Pattern: "--ci",
		Version: "1.0.0",
		Topic: "ci/cd",
		Type: "boolean",
		Example: "bun test --ci",
	},
	{
		Name: "--updateSnapshot",
		Pattern: "-u, --updateSnapshot",
		Version: "1.0.0",
		Topic: "execution",
		Type: "boolean",
		Example: "bun test -u",
	},
	{
		Name: "--color",
		Pattern: "--color",
		Version: "1.0.0",
		Topic: "output",
		Type: "boolean",
		Example: "bun test --color",
	},
	{
		Name: "--no-color",
		Pattern: "--no-color",
		Version: "1.0.0",
		Topic: "output",
		Type: "boolean",
		Example: "bun test --no-color",
	},
	{
		Name: "--verbose",
		Pattern: "--verbose",
		Version: "1.0.0",
		Topic: "output",
		Type: "boolean",
		Example: "bun test --verbose",
	},
	{
		Name: "--silent",
		Pattern: "--silent",
		Version: "1.0.0",
		Topic: "output",
		Type: "boolean",
		Example: "bun test --silent",
	},
	{
		Name: "--timeout",
		Pattern: "--timeout=<ms>",
		Version: "1.0.0",
		Topic: "performance",
		Type: "number",
		Example: "bun test --timeout=30000",
	},
	{
		Name: "--maxWorkers",
		Pattern: "--maxWorkers=<num>",
		Version: "1.0.0",
		Topic: "performance",
		Type: "number",
		Example: "bun test --maxWorkers=4",
	},
	{
		Name: "--runInBand",
		Pattern: "--runInBand",
		Version: "1.0.0",
		Topic: "performance",
		Type: "boolean",
		Example: "bun test --runInBand",
	},
	{
		Name: "--shard",
		Pattern: "--shard=<index/total>",
		Version: "1.0.0",
		Topic: "ci/cd",
		Type: "string",
		Example: "bun test --shard=1/4",
	},
	{
		Name: "--reporters",
		Pattern: "--reporters=<reporters>",
		Version: "1.3.8",
		Topic: "reporting",
		Type: "string[]",
		Example: "bun test --reporters=default --reporters=github-actions",
	},
	{
		Name: "--outputFile",
		Pattern: "--outputFile=<path>",
		Version: "1.3.8",
		Topic: "reporting",
		Type: "string",
		Example: "bun test --outputFile=results.json",
	},
	{
		Name: "--json",
		Pattern: "--json",
		Version: "1.3.8",
		Topic: "reporting",
		Type: "boolean",
		Example: "bun test --json > results.json",
	},
	{
		Name: "--onlyChanged",
		Pattern: "-o, --onlyChanged",
		Version: "1.3.8",
		Topic: "filtering",
		Type: "boolean",
		Example: "bun test -o",
	},
	{
		Name: "--findRelatedTests",
		Pattern: "--findRelatedTests=<paths>",
		Version: "1.3.8",
		Topic: "filtering",
		Type: "string[]",
		Example: "bun test --findRelatedTests=src/math.ts",
	},
	{
		Name: "--passWithNoTests",
		Pattern: "--passWithNoTests",
		Version: "1.3.8",
		Topic: "ci/cd",
		Type: "boolean",
		Example: "bun test --passWithNoTests",
	},
	{
		Name: "--detectOpenHandles",
		Pattern: "--detectOpenHandles",
		Version: "1.3.8",
		Topic: "debug",
		Type: "boolean",
		Example: "bun test --detectOpenHandles",
	},
	{
		Name: "--forceExit",
		Pattern: "--forceExit",
		Version: "1.3.8",
		Topic: "debug",
		Type: "boolean",
		Example: "bun test --forceExit",
	},
	{
		Name: "--config",
		Pattern: "-c, --config=<path>",
		Version: "1.0.0",
		Topic: "config",
		Type: "string",
		Example: "bun test -c ./test.config.ts",
	},
	{
		Name: "--preload",
		Pattern: "--preload=<scripts>",
		Version: "1.3.8",
		Topic: "config",
		Type: "string[]",
		Example: "bun test --preload=./setup.ts",
	},
	{
		Name: "--setupFiles",
		Pattern: "--setupFiles=<paths>",
		Version: "1.3.8",
		Topic: "config",
		Type: "string[]",
		Example: "bun test --setupFiles=./jest.setup.ts",
	},
	{
		Name: "--globalSetup",
		Pattern: "--globalSetup=<path>",
		Version: "1.3.8",
		Topic: "config",
		Type: "string",
		Example: "bun test --globalSetup=./global-setup.ts",
	},
	{
		Name: "--globalTeardown",
		Pattern: "--globalTeardown=<path>",
		Version: "1.3.8",
		Topic: "config",
		Type: "string",
		Example: "bun test --globalTeardown=./global-teardown.ts",
	},
	{
		Name: "--testEnvironment",
		Pattern: "--testEnvironment=<env>",
		Version: "1.3.8",
		Topic: "config",
		Type: "enum",
		Example: "bun test --testEnvironment=node",
	},
	{
		Name: "--moduleNameMapper",
		Pattern: "--moduleNameMapper=<json>",
		Version: "1.3.8",
		Topic: "config",
		Type: "string",
		Example: 'bun test --moduleNameMapper=\'{"^@/(.*)":"<rootDir>/src/$1"}\'',
	},
	{
		Name: "--transformIgnorePatterns",
		Pattern: "--transformIgnorePatterns=<patterns>",
		Version: "1.3.8",
		Topic: "config",
		Type: "string[]",
		Example: "bun test --transformIgnorePatterns='node_modules/(?!lodash)'",
	},
	{
		Name: "--collectCoverageFrom",
		Pattern: "--collectCoverageFrom=<patterns>",
		Version: "1.3.8",
		Topic: "coverage",
		Type: "string[]",
		Example: "bun test --collectCoverageFrom='src/**/*.ts'",
	},
	{
		Name: "--coverageThreshold",
		Pattern: "--coverageThreshold=<json>",
		Version: "1.3.8",
		Topic: "coverage",
		Type: "string",
		Example: 'bun test --coverageThreshold=\'{"global":{"branches":80}}\'',
	},
	{
		Name: "--collectCoverage",
		Pattern: "--collectCoverage",
		Version: "1.3.8",
		Topic: "coverage",
		Type: "boolean",
		Example: "bun test --collectCoverage",
	},
	{
		Name: "--clearCache",
		Pattern: "--clearCache",
		Version: "1.3.8",
		Topic: "debug",
		Type: "boolean",
		Example: "bun test --clearCache",
	},
	{
		Name: "--showConfig",
		Pattern: "--showConfig",
		Version: "1.3.8",
		Topic: "debug",
		Type: "boolean",
		Example: "bun test --showConfig",
	},
	{
		Name: "--debug",
		Pattern: "--debug",
		Version: "1.3.8",
		Topic: "debug",
		Type: "boolean",
		Example: "bun test --debug",
	},
	{
		Name: "--logHeapUsage",
		Pattern: "--logHeapUsage",
		Version: "1.3.8",
		Topic: "debug",
		Type: "boolean",
		Example: "bun test --logHeapUsage",
	},
	{
		Name: "--notify",
		Pattern: "--notify",
		Version: "1.3.8",
		Topic: "reporting",
		Type: "boolean",
		Example: "bun test --notify",
	},
	{
		Name: "--notifyMode",
		Pattern: "--notifyMode=<mode>",
		Version: "1.3.8",
		Topic: "reporting",
		Type: "enum",
		Example: "bun test --notifyMode=failure-success",
	},
	{
		Name: "--errorOnDeprecated",
		Pattern: "--errorOnDeprecated",
		Version: "1.3.8",
		Topic: "execution",
		Type: "boolean",
		Example: "bun test --errorOnDeprecated",
	},
	{
		Name: "--expand",
		Pattern: "-e, --expand",
		Version: "1.3.8",
		Topic: "output",
		Type: "boolean",
		Example: "bun test -e",
	},
	{
		Name: "--lastCommit",
		Pattern: "--lastCommit",
		Version: "1.3.8",
		Topic: "filtering",
		Type: "boolean",
		Example: "bun test --lastCommit",
	},
	{
		Name: "--listTests",
		Pattern: "--listTests",
		Version: "1.3.8",
		Topic: "reporting",
		Type: "boolean",
		Example: "bun test --listTests",
	},
	{
		Name: "--logLevel",
		Pattern: "--logLevel=<level>",
		Version: "1.3.8",
		Topic: "output",
		Type: "enum",
		Example: "bun test --logLevel=debug",
	},
];

export default cliOptionsTable;
