/** File accountability is allow-by-default: every project file belongs in the
 * index unless it is generated, dependency output, VCS data, or a secret env
 * file. Keep this list aligned with .gitignore rather than adding source paths
 * to a fragile positive allowlist. */
export const INDEXED_GLOBS = ['**/*'];
export const INDEX_EXCLUDED_PREFIXES = [
  '.git/',
  'node_modules/',
  'dist/',
  'coverage/',
  'profiles/',
  'reports/',
] as const;

export function isIndexedProjectFile(path: string): boolean {
  if (INDEX_EXCLUDED_PREFIXES.some(prefix => path.startsWith(prefix))) return false;
  if (path === '.env' || (path.startsWith('.env.') && path !== '.env.example')) return false;
  return !path.endsWith('.tgz');
}

export async function projectFiles(cwd = process.cwd()): Promise<string[]> {
  const files = new Set<string>();
  for (const pattern of INDEXED_GLOBS) {
    for await (const path of new Bun.Glob(pattern).scan({ cwd, dot: true, onlyFiles: true })) {
      if (isIndexedProjectFile(path)) files.add(path);
    }
  }
  return [...files].sort((left, right) => left.localeCompare(right));
}

export function renderFilesIndex(files: string[], packageFiles: string[]): string {
  if (packageFiles.length === 0) {
    throw new Error(
      'package.json files must declare a non-empty publish allowlist before generating files.md.'
    );
  }
  const published = packageFiles.map(path => `- \`${path}\``).join('\n');
  const indexed = files.map(path => `- \`${path}\``).join('\n');
  return `# Project files

This index is generated by \`bun run generate:files\`. It documents the source
tree used by the local proof commands; it is not itself included in the package.

## Publish allowlist

${published}

## File index

${indexed}
`;
}

export function parseFilesIndex(markdown: string): string[] {
  const marker = '## File index\n';
  const index = markdown.indexOf(marker);
  if (index === -1) throw new Error('files.md is missing its "File index" section.');
  const files: string[] = [];
  for (const line of markdown.slice(index + marker.length).split('\n')) {
    const match = /^- `([^`]+)`$/.exec(line.trim());
    if (match?.[1]) files.push(match[1]);
  }
  return files;
}
