/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/manager-tools/usersList/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manager-tools/ajax.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve live betting events with filtering options */
        post: operations["getEventsReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlayerList: {
            players?: components["schemas"]["Player"][];
            totalCount?: number;
        };
        Player: {
            id?: string;
            username?: string;
            balance?: number;
            /** @enum {string} */
            status?: "active" | "suspended" | "banned";
        };
        SummaryReport: {
            totalBets?: number;
            totalProfit?: number;
            agentCount?: number;
            /** @enum {string} */
            period?: "daily" | "weekly" | "monthly";
        };
        LastBets: {
            bets?: components["schemas"]["Bet"][];
            totalCount?: number;
        };
        Bet: {
            id?: string;
            playerId?: string;
            amount?: number;
            odds?: number;
            /** @enum {string} */
            result?: "win" | "loss" | "pending";
            /** Format: date-time */
            timestamp?: string;
        };
        UsersReport: {
            users?: components["schemas"]["UserReport"][];
            totalCount?: number;
            period?: {
                /** Format: date */
                start?: string;
                /** Format: date */
                end?: string;
            };
        };
        UserReport: {
            userId?: string;
            username?: string;
            totalBets?: number;
            totalWagered?: number;
            totalWon?: number;
            profit?: number;
            /** Format: date-time */
            lastActivity?: string;
        };
        EventsReport: {
            events?: components["schemas"]["Event"][];
            totalCount?: number;
            filters?: {
                sport?: string;
                league?: string;
                status?: string;
            };
        };
        Event: {
            eventId?: string;
            sport?: string;
            league?: string;
            homeTeam?: string;
            awayTeam?: string;
            /** Format: date-time */
            startTime?: string;
            /** @enum {string} */
            status?: "upcoming" | "live" | "finished";
            score?: {
                home?: number;
                away?: number;
            };
            odds?: {
                homeWin?: number;
                draw?: number;
                awayWin?: number;
            };
            /** @description Number of available betting markets */
            marketCount?: number;
        };
        Error: {
            error: string;
            message: string;
            code?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUsers: {
        parameters: {
            query?: {
                agentNames?: string;
                includeSubAgents?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of players */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerList"];
                };
            };
            /** @description Session expired or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEventsReport: {
        parameters: {
            query: {
                action: "getEventsReport";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /**
                     * @description Row offset for pagination
                     * @default 0
                     */
                    start: number;
                    /**
                     * @description Max events to return
                     * @default 100
                     */
                    limit: number;
                    /** @description Filter by sport type (optional) */
                    sport?: string;
                    /** @description Filter by league (optional) */
                    league?: string;
                    /**
                     * @description Event status filter
                     * @default live
                     * @enum {string}
                     */
                    status?: "upcoming" | "live" | "finished";
                };
            };
        };
        responses: {
            /** @description Paginated events report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsReport"];
                };
            };
            /** @description Session expired / invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
