#!/usr/bin/env bun
// @see https://bun.com/docs/runtime/file-io#reading-files-bun-file — Bun.file
// @see https://bun.com/docs/runtime/file-io#writing-files-bun-write — Bun.write
// @see https://bun.com/reference/bun/argv — Bun.argv
// @see https://bun.com/docs/test/index#run-tests — bun:test
// @see https://bun.com/docs/bundler/executables — --force
// @see https://bun.com/docs/runtime/utils#bun-version — Bun.version
// @see https://bun.com/docs/runtime/child-process#spawn-a-process-bun-spawn — Bun.spawn
// @see https://bun.com/docs/pm/cli/install#dry-run — --dry-run
/**
 * Scaffold a Bun release regression probe file under tests/regression/.
 *
 * Usage (repo root):
 *   bun scripts/new-regression.ts 1.3.15
 *   bun scripts/new-regression.ts --from-current
 *   bun scripts/new-regression.ts 1.3.15 --dry-run
 *   bun run regression:new -- 1.3.15
 *
 * @see tests/regression/README.md
 * @see https://bun.com/blog
 */
import { joinPath } from '../lib/path-bun.ts';

type Args = {
  version: string | null;
  fromCurrent: boolean;
  dryRun: boolean;
  noTest: boolean;
  force: boolean;
  help: boolean;
};

function usage(): string {
  return `Usage: bun scripts/new-regression.ts <bun-version> [flags]
       bun scripts/new-regression.ts --from-current [flags]

Flags:
  --from-current   Use live Bun.version (ignores positional version)
  --dry-run        Print target path + template; do not write
  --no-test        Skip the post-scaffold bun test sanity check
  --force          Overwrite an existing tests/regression/bun-<ver>.test.ts
  -h, --help       Show this help

Example:
  bun scripts/new-regression.ts 1.3.15
`;
}

function parseArgs(argv: string[]): Args {
  const out: Args = {
    version: null,
    fromCurrent: false,
    dryRun: false,
    noTest: false,
    force: false,
    help: false,
  };
  for (const arg of argv) {
    if (arg === '-h' || arg === '--help') out.help = true;
    else if (arg === '--from-current') out.fromCurrent = true;
    else if (arg === '--dry-run') out.dryRun = true;
    else if (arg === '--no-test') out.noTest = true;
    else if (arg === '--force') out.force = true;
    else if (arg.startsWith('-')) {
      throw new Error(`Unknown flag: ${arg}\n${usage()}`);
    } else if (out.version === null) {
      out.version = arg;
    } else {
      throw new Error(`Unexpected argument: ${arg}\n${usage()}`);
    }
  }
  return out;
}

function isSemver(v: string): boolean {
  return /^\d+\.\d+\.\d+$/.test(v);
}

function scaffoldSource(version: string, generatedOn: string, runtimeVersion: string): string {
  const blog = `https://bun.com/blog/bun-v${version}`;
  return `// @see ${blog}
// Full-release regression probes for Bun v${version} (Features · Performance · Bugfixes).
// Runs on Bun ≥ ${version} (newer runtimes must keep these fixed).
//
// Generated by scripts/new-regression.ts on ${generatedOn}
// Scaffold runtime: Bun ${runtimeVersion}
//
// Skips (fixSkip / always-skip) — document each env-specific skip here:
//   1. …
//
//   bun test tests/regression/bun-${version}.test.ts
import { describe, expect, test } from 'bun:test';
// Prefer fixTest/fixSkip for real probes (skip on Bun < MIN_VERSION).
// import { tempRoot, shortTempRoot } from './shared.ts';
import { releaseTest } from './shared.ts';

const MIN_VERSION = '${version}';
const BLOG = '${blog}';
const BLOG_BUGFIXES = \`\${BLOG}#bugfixes\`;

const { test: fixTest, skipIf: fixSkip } = releaseTest(MIN_VERSION);

describe(\`Bun \${MIN_VERSION} Features (\${BLOG})\`, () => {
  // Scaffold smoke always runs (even when Bun.version < MIN_VERSION) so authors can iterate.
  // Delete this test when the first real Features probe lands.
  test('scaffold: Features section ready (delete when first probe lands)', () => {
    expect(MIN_VERSION).toBe('${version}');
  });

  // Version-gated example — runs only when Bun ≥ MIN_VERSION. Prefer fixTest for real probes.
  fixTest('scaffold: release gate sees Bun ≥ MIN_VERSION', () => {
    expect(Bun.version.split('.').length).toBe(3);
  });

  // TODO: replace with blog Features probes (one fixTest per bullet).
  fixSkip(true)('TODO: Features — probe from ${blog}', () => {
    /* replace with a real assertion; keep skip reason in the file header */
  });
});

describe(\`Bun \${MIN_VERSION} Performance smokes (\${BLOG})\`, () => {
  test('scaffold: Performance section ready (delete when first probe lands)', () => {
    expect(BLOG).toContain('bun-v${version}');
  });

  // TODO: correctness smokes for speed claims — do not gate CI on wall-clock µs.
  fixSkip(true)('TODO: Performance — timing claim (manual bench only)', () => {
    /* log locally; skip CI thresholds */
  });
});

describe(\`Bun \${MIN_VERSION} bugfixes — Node.js compatibility (\${BLOG_BUGFIXES})\`, () => {
  test('scaffold: Bugfixes (Node) section ready (delete when first probe lands)', () => {
    expect(BLOG_BUGFIXES.endsWith('#bugfixes')).toBe(true);
  });

  // TODO: one fixTest per Bugfixes bullet under "Node.js compatibility".
  fixSkip(true)('TODO: Bugfixes — Node.js compatibility probe', () => {
    /* … */
  });
});

describe(\`Bun \${MIN_VERSION} bugfixes — Bun APIs (\${BLOG_BUGFIXES})\`, () => {
  fixSkip(true)('TODO: Bugfixes — Bun APIs probe', () => {
    /* … */
  });
});

describe(\`Bun \${MIN_VERSION} bugfixes — Web APIs (\${BLOG_BUGFIXES})\`, () => {
  fixSkip(true)('TODO: Bugfixes — Web APIs probe', () => {
    /* … */
  });
});

describe(\`Bun \${MIN_VERSION} bugfixes — bundler / bun test / shell / Windows (\${BLOG_BUGFIXES})\`, () => {
  fixSkip(true)('TODO: Bugfixes — bundler / test / shell / Windows probe', () => {
    /* … */
  });
});
`;
}

async function updateReadme(readmePath: string, version: string, dryRun: boolean): Promise<void> {
  const readme = Bun.file(readmePath);
  if (!(await readme.exists())) {
    console.warn(`⚠️  ${readmePath} missing — skip README update`);
    return;
  }

  let text = await readme.text();
  const linkLine = `| \`${version}\` | [\`bun-${version}.test.ts\`](./bun-${version}.test.ts) | [blog](https://bun.com/blog/bun-v${version}) |`;
  if (text.includes(`bun-${version}.test.ts`)) {
    console.log(`ℹ️  README already lists bun-${version}.test.ts`);
    return;
  }

  const marker = '<!-- regression-release-table -->';
  if (text.includes(marker)) {
    text = text.replace(marker, `${marker}\n${linkLine}`);
  } else if (/\| Version \| File \| Blog \|/.test(text)) {
    text = text.replace(
      /(\| Version \| File \| Blog \|\n\|[- ]+\|[- ]+\|[- ]+\|)/,
      `$1\n${linkLine}`
    );
  } else {
    text += `\n## Releases\n\n| Version | File | Blog |\n| ------- | ---- | ---- |\n${linkLine}\n`;
  }

  if (dryRun) {
    console.log(`DRY-RUN would update README with:\n${linkLine}`);
    return;
  }
  await Bun.write(readmePath, text);
  console.log(`✅ Updated ${readmePath}`);
}

async function main(): Promise<number> {
  let args: Args;
  try {
    args = parseArgs(Bun.argv.slice(2));
  } catch (e) {
    console.error(String((e as Error).message));
    return 2;
  }

  if (args.help) {
    console.log(usage());
    return 0;
  }

  const version = args.fromCurrent ? Bun.version : args.version;
  if (!version) {
    console.error(usage());
    return 2;
  }
  if (!isSemver(version)) {
    console.error(`Error: version must be semver X.Y.Z (got ${JSON.stringify(version)})`);
    return 2;
  }

  const root = joinPath(import.meta.dir, '..');
  const targetRel = `tests/regression/bun-${version}.test.ts`;
  const targetAbs = joinPath(root, targetRel);
  const readmeAbs = joinPath(root, 'tests/regression/README.md');
  const generatedOn = new Date().toISOString().slice(0, 10);
  const source = scaffoldSource(version, generatedOn, Bun.version);

  const targetExists = await Bun.file(targetAbs).exists();
  if (targetExists && !args.force && !args.dryRun) {
    console.error(`Error: ${targetRel} already exists (pass --force to overwrite)`);
    return 1;
  }

  if (args.dryRun) {
    console.log(`DRY-RUN target: ${targetRel}`);
    console.log('---');
    console.log(source);
    await updateReadme(readmeAbs, version, true);
    return 0;
  }

  await Bun.write(targetAbs, source);
  console.log(`✅ Created ${targetRel}`);
  await updateReadme(readmeAbs, version, false);

  if (!args.noTest) {
    console.log(`Running sanity check: bun test ${targetRel}`);
    const proc = Bun.spawn([process.execPath, 'test', targetRel], {
      cwd: root,
      stdout: 'inherit',
      stderr: 'inherit',
    });
    const code = await proc.exited;
    if (code !== 0) {
      console.error(`⚠️  bun test exited ${code} — scaffold may need a tweak`);
      return code;
    }
  }

  console.log(`🎉 Done. Open ${targetRel} and replace TODOs with blog probes.`);
  console.log(`   Blog: https://bun.com/blog/bun-v${version}`);
  return 0;
}

if (import.meta.main) {
  process.exit(await main());
}
