#!/usr/bin/env bun
// @see https://bun.com/reference/bun/argv — Bun.argv
// @see https://bun.com/docs/runtime/child-process#blocking-api-bun-spawnsync — Bun.spawnSync
// @see https://bun.com/docs/runtime/shell#getting-started — Bun.$
// @see https://bun.com/docs/pm/cli/install#dry-run — --dry-run
// @see https://bun.com/docs/runtime/file-io#writing-files-bun-write — Bun.write
/**
 * Sync monorepo public catalog → deeplink package public-catalog.json + rebuild tarball.
 *
 *   bun run bookmakers:prepare-publish
 *
 * Package root (artifact lane, not packages/ workspace):
 *   artifacts/deeplink-automation/packages/bookmakers/
 *
 * Then publish (needs R2):
 *   bun run factory:publish artifacts/deeplink-automation/packages/bookmakers/factorywager-bookmakers-0.4.0.tgz \
 *     --name @factorywager/bookmakers --version 0.4.0 --type library
 */
import { applyUnknownLongOptionGuardFor } from '../lib/docs/ref-id-tool-flags.ts';
import { joinPath } from '../lib/path-bun.ts';

const PACKAGE_DIR = 'artifacts/deeplink-automation/packages/bookmakers';
const PUBLIC_MIRROR = 'public/registry/bookmakers.json';
const VERSION = '0.4.0';

async function main(): Promise<void> {
  const argv = applyUnknownLongOptionGuardFor('bookmakers:prepare-publish', Bun.argv.slice(2));
  const dry = argv.includes('--dry-run');
  if (!(await Bun.file(PUBLIC_MIRROR).exists())) {
    throw new Error(`missing ${PUBLIC_MIRROR}`);
  }
  if (!(await Bun.file(joinPath(PACKAGE_DIR, 'package.json')).exists())) {
    throw new Error(
      `missing package at ${PACKAGE_DIR} — expected deeplink-automation bookmakers package`
    );
  }

  const catalog = JSON.parse(await Bun.file(PUBLIC_MIRROR).text()) as {
    schemaVersion: number;
    bookmakers: Record<string, unknown>;
    audit?: { ok: boolean };
    summary?: unknown;
    artifact?: { version?: string };
  };

  if (catalog.schemaVersion !== 2) {
    throw new Error(`expected schemaVersion 2 public catalog, got ${catalog.schemaVersion}`);
  }
  if (catalog.audit && catalog.audit.ok === false) {
    throw new Error('public catalog audit not ok — fix before publish');
  }

  const packageCatalog = {
    schemaVersion: 2,
    generatedAt: new Date().toISOString(),
    artifact: {
      name: '@factorywager/bookmakers',
      version: VERSION,
      source: 'package',
    },
    bookmakers: catalog.bookmakers,
    audit: catalog.audit ?? { ok: true, issues: [] },
    summary: catalog.summary,
  };

  const catalogPath = joinPath(PACKAGE_DIR, 'public-catalog.json');
  const catalogTs = `// Generated by scripts/prepare-bookmakers-publish.ts — do not hand-edit.
import catalog from "./public-catalog.json";

export const PUBLIC_CATALOG = catalog;
export const PUBLIC_BOOKMAKERS = catalog.bookmakers;
export type PublicBookmaker = (typeof PUBLIC_BOOKMAKERS)[keyof typeof PUBLIC_BOOKMAKERS];
`;

  const pkgJsonPath = joinPath(PACKAGE_DIR, 'package.json');
  const pkgJson = JSON.parse(await Bun.file(pkgJsonPath).text()) as { version?: string };
  pkgJson.version = VERSION;

  if (dry) {
    console.log(
      `--dry-run: would write ${catalogPath} (${Object.keys(catalog.bookmakers).length} books) + package version ${VERSION}`
    );
    return;
  }

  await Bun.write(catalogPath, `${JSON.stringify(packageCatalog, null, 2)}\n`);
  await Bun.write(joinPath(PACKAGE_DIR, 'public-catalog.ts'), catalogTs);
  await Bun.write(pkgJsonPath, `${JSON.stringify(pkgJson, null, 2)}\n`);

  // Build dist if tsconfig present
  const tsc = joinPath(PACKAGE_DIR, 'tsconfig.build.json');
  if (await Bun.file(tsc).exists()) {
    const build = Bun.spawnSync(['bun', 'x', 'tsc', '-p', 'tsconfig.build.json'], {
      cwd: PACKAGE_DIR,
      stdout: 'inherit',
      stderr: 'inherit',
    });
    if (build.exitCode !== 0) {
      console.warn('tsc build failed — packing sources only');
    }
  }

  // Also copy PUBLIC into dist for tarball consumers
  await Bun.$`mkdir -p ${joinPath(PACKAGE_DIR, 'dist')}`.quiet();
  await Bun.write(
    joinPath(PACKAGE_DIR, 'dist/public-catalog.json'),
    `${JSON.stringify(packageCatalog, null, 2)}\n`
  );

  const tgzName = `factorywager-bookmakers-${VERSION}.tgz`;
  const tgzPath = joinPath(PACKAGE_DIR, tgzName);
  // npm-style package/ prefix
  const pack = Bun.spawnSync(
    ['tar', '-czf', tgzName, '--exclude', '*.tgz', '--exclude', 'node_modules', '.'],
    { cwd: PACKAGE_DIR, stdout: 'inherit', stderr: 'inherit' }
  );
  if (pack.exitCode !== 0) throw new Error('tar pack failed');

  console.log(`✓ ${catalogPath}`);
  console.log(`✓ ${tgzPath}`);
  console.log(
    `Next: bun run factory:publish ${tgzPath} --name @factorywager/bookmakers --version ${VERSION} --type library`
  );
  console.log(
    `Then: bun lib/factory/cli.ts snapshot public/registry/registry.json && bun run bookmakers:bake`
  );
}

if (import.meta.main) {
  await main();
}
