// infrastructure/types.d.ts - Golden Matrix v2.4.1 Feature Registry
// Generated by CompileTimeFlagEngine (Component #86)

declare module "bun:bundle" {
  interface Registry {
    features:
      // Infrastructure (Components #1-85)
      | "MCP_ENABLED"
      | "QUANTUM_READY"
      | "PREMIUM"
      | "DEBUG"
      | "CONFIG_VERSION_STABLE"

      // Package Manager (Components #65-70)
      | "NO_PEER_DEPS_OPT"
      | "NPMRC_EMAIL"
      | "SELECTIVE_HOISTING"
      | "PACK_ENFORCER"

      // Native/Stability (Components #71-95)
      | "SOURCEMAP_INTEGRITY"           // Component #71
      | "NAPI_THREADSAFE"               // Component #72
      | "WS_FRAGMENT_GUARD"             // Component #73
      | "WORKER_THREAD_SAFETY"          // Component #74
      | "YML_DOC_END_FIX"               // Component #75
      | "BUNX_UTF8_FIX"                 // Component #76
      | "MYSQL_PARAM_GUARD"             // Component #77
      | "MYSQL_TLS_FIX"                 // Component #78
      | "MYSQL_IDLE_FIX"                // Component #79
      | "REDIS_URL_VALIDATE"            // Component #80
      | "S3_ETAG_FIX"                   // Component #81
      | "FFI_ERROR_SURFACE"             // Component #82
      | "WS_COOKIE_FIX"                 // Component #83
      | "NODEJS_COMPAT_PATCH"           // Component #84
      | "CLOUDFLARE_SEC_PATCH"          // Component #85
      | "COMPILE_TIME_VALIDATION"       // Component #86
      | "STRING_WIDTH_OPT"              // Component #87
      | "V8_TYPE_CHECK"                 // Component #88
      | "S3_CONTENT_DISPOSITION"        // Component #89
      | "NPMRC_ENV_EXPAND"              // Component #90
      | "SELECTIVE_HOIST_CTRL"          // Component #91
      | "NODEJS_READLINES"              // Component #92
      // Note: Component #93 uses SOURCEMAP_INTEGRITY (same as #71)
      // Note: Component #94 uses NAPI_THREADSAFE (same as #72)
      // Note: Component #95 uses WS_FRAGMENT_GUARD (same as #73)

      // Master flags
      | "BUN_PM_OPTIMIZATIONS"
      | "NATIVE_STABILITY"
      | "GOLDEN_MATRIX_V2_4_1_FINAL";
  }
}

// Type definitions for infrastructure components
export interface CompileTimeFlagEngine {
  augmentRegistry(): string;
  validateFeatureFlag(flag: string): boolean;
  analyzeBundleDeadCode(bundlePath: string): Promise<{
    eliminatedBytes: number;
    eliminatedLines: number;
    features: string[];
  }>;
  applyDeadCodeElimination(code: string, enabledFeatures: string[]): string;
}

export interface UnicodeStringWidthEngine {
  calculateWidth(text: string): number;
}

export interface V8TypeCheckAPI {
  isMap(value: any): boolean;
  isArray(value: any): boolean;
  isInt32(value: any): boolean;
  isBigInt(value: any): boolean;
  createNapiTypeChecker(): any;
}

export interface S3ContentDisposition {
  setContentDisposition(
    key: string,
    disposition: 'inline' | 'attachment',
    filename?: string
  ): any;
  uploadWithDisposition(
    client: any,
    key: string,
    data: Buffer,
    options: { disposition: 'inline' | 'attachment'; filename?: string }
  ): Promise<void>;
}

export interface NpmrcEnvExpander {
  expandValue(value: string, env: Record<string, string>): string;
  loadNpmrcWithExpansion(path: string): Promise<Record<string, string>>;
  expandValueSecure(value: string, env: Record<string, string>): string;
}

export interface SelectiveHoistController {
  getHoistPatterns(config: any): string[];
  shouldHoist(packageName: string, patterns: string[]): boolean;
  createHoistedSymlinks(
    packageName: string,
    targetPath: string,
    patterns: string[]
  ): Promise<void>;
  parseNpmrcHoistPatterns(lines: string[]): string[];
}

export interface FileHandleReadLinesEngine {
  readLines(
    filePath: string,
    options?: { encoding?: string; autoClose?: boolean; signal?: AbortSignal }
  ): AsyncGenerator<string>;
}

export interface SourcemapIntegrityValidator {
  validateBuildSourcemaps(
    buildResult: any,
    compileMode: boolean
  ): Promise<{ valid: boolean; errors: string[] }>;
  fixCompileOptions(options: any): any;
  rewriteImportMeta(code: string): string;
}

export interface NAPIThreadSafetyGuard {
  createThreadSafeFunction(
    fn: (value: any) => any,
    options?: any
  ): any;
}

export interface WebSocketFragmentGuard {
  createWebSocket(ws: any): any;
}

export interface InfrastructureHealthCheck {
  version: string;
  activeComponents: number;
  zeroCostEliminated: number;
  status: string;
}

export interface Infrastructure {
  CompileTimeFlagEngine: CompileTimeFlagEngine;
  UnicodeStringWidthEngine: UnicodeStringWidthEngine;
  V8TypeCheckAPI: V8TypeCheckAPI;
  S3ContentDisposition: S3ContentDisposition;
  NpmrcEnvExpander: NpmrcEnvExpander;
  SelectiveHoistController: SelectiveHoistController;
  FileHandleReadLinesEngine: FileHandleReadLinesEngine;
  SourcemapIntegrityValidator: SourcemapIntegrityValidator;
  NAPIThreadSafetyGuard: NAPIThreadSafetyGuard;
  WebSocketFragmentGuard: WebSocketFragmentGuard;
  healthCheck(): Promise<InfrastructureHealthCheck>;
  registry: {
    INFRASTRUCTURE: string[];
    PACKAGE_MANAGER: string[];
    NATIVE_STABILITY: string[];
    MASTER: string[];
  };
}

// Global augmentation for Bun features
declare global {
  function feature(name: string): boolean;

  namespace Bun {
    function stringWidth(text: string): number;
    function file(path: string): {
      text(): Promise<string>;
      json(): Promise<any>;
      size: number;
    };
    function write(path: string, content: string | Blob | ArrayBuffer | DataView | Uint8Array): Promise<number>;
    const env: Record<string, string | undefined>;
  }
}

// Type for RegExpMatchArray with index signature
interface RegExpMatchArrayWithGroups extends RegExpMatchArray {
  groups?: Record<string, string>;
}

export {};
