#!/usr/bin/env bun
/**
 * Minimal test script for profiling
 * Auto-generated by generate-all-profiles.ts
 */

// Try to import the project's main exports
try {
  // Attempt common import patterns
  const pkg = await import('./package.json');
  console.log('Project:', pkg.name || 'unknown');
  
  // Try importing index files
  try {
    await import('./index.ts');
  } catch {}
  
  try {
    await import('./src/index.ts');
  } catch {}
  
  try {
    await import('./lib/index.ts');
  } catch {}
  
  // Small delay to ensure profiling captures the state
  await new Promise(resolve => setTimeout(resolve, 100));
  
  console.log('Profile test completed');
} catch (error) {
  console.error('Error in profile test:', error);
}
