// dns-prefetch.ts — auto-generated by scan.ts --fix-dns
// These domains are explicitly prefetched at runtime by Bun for lower latency
// Re-run: bun run ../scanner/scan.ts --fix-dns

import { dns } from "bun";

dns.prefetch("api.fire22.com", 443);
dns.prefetch("dev.registry.sportsbet.com", 443);
dns.prefetch("localhost", 443);
dns.prefetch("registry.factory-wager.com", 443);
dns.prefetch("registry.npmjs.org", 443);
dns.prefetch("registry.sportsbet.com", 443);
