// @see https://bun.com/docs/runtime/file-io#reading-files-bun-file — Bun.file
/**
 * partner-surface-docs.ts — generate Markdown tables from inventory linking metadata.
 *
 * @see docs/design/partner-surface-inventory.md
 * @see docs/design/partner-surface-inventory.generated.md
 */
import {
  buildPartnerSurfaceInventory,
  partnerDeskHrefs,
  type PartnerSurfaceInventory,
  type PartnerSurfaceRow,
} from './partner-surface-inventory.ts';

export { partnerDeskHrefs };

export const PARTNER_SURFACE_GENERATED_DOC_REL =
  'docs/design/partner-surface-inventory.generated.md';

export type LivePartnerCodeRow = {
  readonly code: string;
  readonly phase?: string;
};

function cell(value: string | undefined | null): string {
  const t = (value ?? '').trim();
  return t ? `\`${t}\`` : '—';
}

function sortByToken(a: PartnerSurfaceRow, b: PartnerSurfaceRow): number {
  return a.token.localeCompare(b.token) || a.id.localeCompare(b.id);
}

/**
 * Render committed generated Markdown (stable — no wall-clock timestamps).
 */
export function formatPartnerSurfaceGeneratedMarkdown(
  inv: PartnerSurfaceInventory = buildPartnerSurfaceInventory('—'),
  liveCodes: readonly LivePartnerCodeRow[] | null = null
): string {
  const taxonomy = inv.rows
    .filter(r => r.aspect === 'taxonomy')
    .slice()
    .sort(sortByToken);
  const brands = inv.rows
    .filter(r => r.aspect === 'brand')
    .slice()
    .sort(sortByToken);
  const boards = inv.rows
    .filter(r => r.aspect === 'chrome-nav' || r.aspect === 'portal-board')
    .slice()
    .sort((a, b) => {
      const ah = a.href ?? '';
      const bh = b.href ?? '';
      return ah.localeCompare(bh) || a.token.localeCompare(b.token);
    });

  const lines: string[] = [
    '# Partner surface inventory (generated)',
    '',
    '> Generated by `bun run partner-surface-inventory:docs` from',
    '> `lib/docs/partner-surface-inventory.ts`. Do not edit by hand.',
    '> Check freshness: `bun run partner-surface-inventory:docs:check`.',
    '',
    `**Claim** \`${inv.claim}\` · schema v${inv.schemaVersion} · principle \`${inv.principle}\``,
    '',
    '| Machine | Token |',
    '| ------- | ----- |',
    `| sessionLane | \`${inv.sessionLane.id}\` |`,
    `| chromeDomain | \`${inv.chromeDomain.id}\` (${inv.chromeDomain.label}) |`,
    `| conceptDomain | \`${inv.conceptDomain.id}\` |`,
    `| commitScopeHints | ${inv.commitScopeHints.map(h => `\`${h}\``).join(', ') || '—'} |`,
    '',
    '## Domains',
    '',
    '| Machine | Token | Href | Notes |',
    '| ------- | ----- | ---- | ----- |',
  ];

  for (const r of taxonomy) {
    lines.push(
      `| \`${r.machine ?? '—'}\` | \`${r.token}\` | ${cell(r.href)} | ${r.notes ?? r.properties[0] ?? '—'} |`
    );
  }

  lines.push(
    '',
    '## Brands',
    '',
    '| Brand | Domain | Registry | Active | Category | Href | Mint |',
    '| ----- | ------ | -------- | ------ | -------- | ---- | ---- |'
  );

  for (const r of brands) {
    const bag = r.brand;
    if (!bag) continue;
    const typeNote = r.typeOrExport && r.typeOrExport !== r.token ? ` → \`${r.typeOrExport}\`` : '';
    lines.push(
      `| \`${r.token}\`${typeNote} | \`${bag.domain}\` | ${cell(bag.registryRef)} | ${bag.isActive ? 'yes' : 'no'} | \`${bag.category}\` | ${cell(r.href)} | \`${bag.mintAuthority}\` |`
    );
  }

  lines.push(
    '',
    '## Brand status',
    '',
    '| Brand | Active | Deprecated | Reason | Replaced by |',
    '| ----- | ------ | ---------- | ------ | ----------- |'
  );

  for (const r of brands) {
    const bag = r.brand;
    if (!bag) continue;
    lines.push(
      `| \`${r.token}\` | ${bag.isActive ? 'yes' : 'no'} | ${cell(bag.deprecatedAt)} | ${bag.deprecationReason?.trim() ? bag.deprecationReason.trim() : '—'} | ${cell(bag.replacedBy)} |`
    );
  }

  lines.push(
    '',
    '## Partner boards',
    '',
    '| Aspect | Token | Href | Registry |',
    '| ------ | ----- | ---- | -------- |'
  );

  for (const r of boards) {
    const reg = r.chromeNav?.registryArtifact ?? '—';
    lines.push(
      `| \`${r.aspect}\` | \`${r.token}\` | ${cell(r.href)} | ${reg === '—' ? '—' : `\`${reg}\``} |`
    );
  }

  lines.push('', '## Live PartnerCodes', '');

  if (liveCodes === null) {
    lines.push('_partners-ops bake absent — run partners-ops bake to populate live codes._', '');
  } else if (liveCodes.length === 0) {
    lines.push('_partners-ops present but contains no partner codes._', '');
  } else {
    lines.push(
      '| Code | Partners | Account | History | Phase |',
      '| ---- | -------- | ------- | ------- | ----- |'
    );
    for (const row of [...liveCodes].sort((a, b) => a.code.localeCompare(b.code))) {
      const hrefs = partnerDeskHrefs(row.code);
      lines.push(
        `| \`${row.code}\` | ${cell(hrefs.partnersHref)} | ${cell(hrefs.accountHref)} | ${cell(hrefs.historyHref)} | ${row.phase ? `\`${row.phase}\`` : '—'} |`
      );
    }
    lines.push('');
  }

  lines.push(
    '## Regenerate',
    '',
    '```bash',
    'bun run partner-surface-inventory:docs',
    'bun run partner-surface-inventory:docs:check',
    '```',
    ''
  );

  return `${lines.join('\n')}`;
}

/** Parse PartnerCode rows from a partners-ops-shaped artifact. */
export function livePartnerCodesFromPartnersOps(
  // eslint-disable-next-line harness/no-unknown-function-param -- registry JSON edge
  artifact: unknown
): readonly LivePartnerCodeRow[] {
  if (typeof artifact !== 'object' || artifact === null) return [];
  const partners = (artifact as { partners?: unknown }).partners;
  if (!Array.isArray(partners)) return [];
  const out: LivePartnerCodeRow[] = [];
  for (const p of partners) {
    if (typeof p !== 'object' || p === null) continue;
    const rec = p as Record<string, unknown>;
    const raw = rec.code ?? rec.partnerCode;
    if (typeof raw !== 'string' || !raw.trim()) continue;
    const phase = typeof rec.phase === 'string' ? rec.phase : undefined;
    out.push({ code: raw.trim().toUpperCase(), phase });
  }
  return out;
}

export async function loadLivePartnerCodes(
  partnersOpsAbsPath: string
): Promise<{ codes: readonly LivePartnerCodeRow[] | null; warned: boolean }> {
  const file = Bun.file(partnersOpsAbsPath);
  if (!(await file.exists())) {
    return { codes: null, warned: true };
  }
  try {
    const artifact = await file.json();
    return { codes: livePartnerCodesFromPartnersOps(artifact), warned: false };
  } catch {
    return { codes: null, warned: true };
  }
}
