#!/usr/bin/env bun
// @see https://bun.com/docs/bundler/bytecode#combining-with-other-optimizations — --minify
/**
 * Optional portal CSS build — Bun lowers modern CSS (nesting, :lang/:is/:not,
 * logical props, media ranges, …) and can unlock deferred features
 * (light-dark, color-mix, relative/LAB/P3) with legacy fallbacks.
 *
 * Static-first default: pages still link `/portal/style.css`.
 * Opt in: point `<link>` at `/portal/dist/style.css` after this build.
 *
 * Dual output note: Bun does **not** expose a browserslist dual-file CSS API.
 * One `Bun.build` already lowers nesting/:lang/:is/logical/media to legacy-safe
 * CSS (LightningCSS defaults: Chrome 87+, Firefox 78+, Safari 14+, Edge 88+).
 * Treat this as:
 *   modern source  → /portal/style.css
 *   lowered build  → /portal/dist/style.css  (+ style.min.css with --minify)
 *
 * Usage:
 *   bun tools/build-portal-css.ts
 *   bun tools/build-portal-css.ts --minify
 *   bun tools/build-portal-css.ts --check
 *
 * @see https://bun.com/docs/bundler#content-types — Asset Processing / Content types
 * @see https://bun.com/docs/bundler/loaders#css — CSS loader (`.css` → bundled stylesheet)
 * @see https://bun.com/docs/bundler/index#basic-example — Bun.build
 * @see https://bun.com/docs/bundler/css — CSS syntax lowering
 * @see https://bun.com/docs/bundler/html-static — HTML-entry auto-bundle (alt path)
 * @see https://bun.com/docs/runtime/file-io — Bun.file / Bun.write
 */
import { joinPath, resolvePath } from '../lib/path-bun.ts';
import { syncPortalTheme } from './sync-portal-theme.ts';

const ROOT = resolvePath(import.meta.dir, '..');
const SOURCE = joinPath(ROOT, 'public/portal/style.css');
const OUTDIR = joinPath(ROOT, 'public/portal/dist');

/** Public URL prefix for any `url()` / asset paths the CSS loader rewrites. */
const PUBLIC_PATH = '/portal/dist/';

const minify = Bun.argv.includes('--minify');
const check = Bun.argv.includes('--check');

type BuildOpts = {
  naming: string;
  minify: boolean;
};

async function buildCss(opts: BuildOpts) {
  // Explicit css loader — default for .css, documented for Asset Processing clarity.
  // @see https://bun.com/docs/bundler/loaders#css
  // @see https://bun.com/docs/bundler#content-types
  return Bun.build({
    entrypoints: [SOURCE],
    outdir: OUTDIR,
    naming: opts.naming,
    minify: opts.minify,
    publicPath: PUBLIC_PATH,
    loader: {
      '.css': 'css',
    },
  });
}

async function main(): Promise<void> {
  // Keep theme-tokens.css in sync (jsonc loader) before css loader bundles @import.
  await syncPortalTheme();

  const src = Bun.file(SOURCE);
  if (!(await src.exists())) {
    console.error(`Missing source: ${SOURCE}`);
    process.exit(1);
  }

  // Always emit readable lowered CSS; optionally also emit minified.
  const lowered = await buildCss({ naming: 'style.css', minify: false });

  if (!lowered.success) {
    console.error('portal CSS build failed:');
    for (const log of lowered.logs) console.error(log);
    process.exit(1);
  }

  const outPath = lowered.outputs[0]?.path ?? joinPath(OUTDIR, 'style.css');
  const size = Bun.file(outPath).size;
  const kind = lowered.outputs[0]?.kind ?? 'asset';

  let minPath: string | undefined;
  let minSize: number | undefined;
  if (minify) {
    const minified = await buildCss({ naming: 'style.min.css', minify: true });
    if (!minified.success) {
      console.error('portal CSS minify failed:');
      for (const log of minified.logs) console.error(log);
      process.exit(1);
    }
    minPath = minified.outputs[0]?.path ?? joinPath(OUTDIR, 'style.min.css');
    minSize = Bun.file(minPath).size;
  }

  const readme = [
    '# Portal CSS build artifacts',
    '',
    'Generated by `bun run portal:css:build` (`Bun.build` + **css** loader).',
    '',
    'Asset Processing path:',
    '- [Content types](https://bun.com/docs/bundler#content-types) — `.css` row',
    '- [CSS loader](https://bun.com/docs/bundler/loaders#css) — parse, `@import`, `url()`, lowering',
    '- [bundler/css](https://bun.com/docs/bundler/css) — nesting, `:lang()`, logical props, …',
    '',
    '| File | Role |',
    '|------|------|',
    '| `style.css` | Lowered / vendor-prefixed (Bun default browser targets) |',
    '| `style.min.css` | Same + minify (`--minify`) |',
    '',
    `\`publicPath\`: \`${PUBLIC_PATH}\` (prefixes rewritten asset URLs).`,
    '',
    'Source of truth remains `../style.css` (static-first).',
    'There is no separate browserslist dual-modern file — Bun lowers in one pass.',
    '',
  ].join('\n');
  await Bun.write(joinPath(OUTDIR, 'README.md'), readme);

  console.log(`Built portal CSS → ${outPath}`);
  console.log(`  source: ${SOURCE}`);
  console.log(`  loader: css (Asset Processing) · kind=${kind}`);
  console.log(`  publicPath: ${PUBLIC_PATH}`);
  console.log(`  size:   ${size} bytes (lowered)`);
  if (minPath) console.log(`  minify: ${minPath} (${minSize} bytes)`);
  console.log(`  docs:   bundler#content-types · bundler/loaders#css · bundler/css`);
  console.log('');
  console.log('Serve static (default):  /portal/style.css');
  console.log('Serve lowered (opt-in):  /portal/dist/style.css');
  if (minPath) console.log('Serve minified:         /portal/dist/style.min.css');

  if (check && size < 1000) {
    console.error('--check: built CSS unexpectedly small');
    process.exit(1);
  }
}

if (import.meta.main) {
  main().catch(e => {
    console.error(e instanceof Error ? e.message : e);
    process.exit(1);
  });
}

export { SOURCE, OUTDIR, main as buildPortalCss };
