#!/usr/bin/env bun
// @see https://bun.com/docs/runtime/file-io — Bun.file / Bun.write
// @see https://bun.com/reference/bun/argv — Bun.argv
import { joinPath } from '../lib/path-bun.ts';
import {
  auditRegulationPolicyCatalog,
  JURISDICTION_CATALOG,
  REGULATION_POLICY_CATALOG,
  resolveRegulationPolicy,
} from '../lib/operations/regulation-policy-catalog.ts';

export const JURISDICTIONS_DOC_PATH = 'docs/JURISDICTIONS.md';

function money(value: number | null): string {
  return value == null ? '—' : `$${value.toLocaleString('en-US')}`;
}

export function renderJurisdictionsDocs(): string {
  const audit = auditRegulationPolicyCatalog();
  if (!audit.ok) {
    throw new Error(`Cannot generate jurisdictions docs: ${audit.errors} policy audit errors`);
  }
  const lines = [
    '# Jurisdiction policy catalog',
    '',
    '> Generated by `bun run jurisdictions:docs` from `lib/operations/regulation-policy-catalog.ts`.',
    '> These are internal operational reference policies, not external legal citations.',
    '',
    `**Catalog:** ${audit.active} active policies · ${JURISDICTION_CATALOG.length} jurisdictions · ${audit.warnings} warnings`,
    '',
  ];
  for (const jurisdiction of JURISDICTION_CATALOG) {
    lines.push(`## ${jurisdiction.label} (${jurisdiction.stateCode})`, '');
    lines.push(
      `Authority: \`${jurisdiction.authority}\` · default age: ${jurisdiction.defaultAge}+ · source: \`${jurisdiction.sourceRef}\``,
      ''
    );
    lines.push(
      '| Policy | Status | Risk | Enforcement | Limit | Daily | Weekly | Effective | Bet types | Source |',
      '|---|---|---|---|---:|---:|---:|---|---|---|'
    );
    for (const policy of REGULATION_POLICY_CATALOG.filter(
      entry => entry.jurisdiction === jurisdiction.stateCode
    )) {
      const resolved = resolveRegulationPolicy(policy);
      lines.push(
        `| [${policy.label}](https://score.factory-wager.com/portal/glossary/#glossary:${policy.key}) · \`${resolved.policyCode}\` | ${policy.status} | ${policy.riskTier} | ${policy.enforcementAction} | ${money(policy.maxBet)} | ${money(resolved.dailyLimit)} | ${money(resolved.weeklyLimit)} | ${policy.effectiveDate} | ${policy.allowedBetTypes.join(', ')} | \`${policy.sourceRef}\` |`
      );
    }
    lines.push('');
  }
  lines.push(
    '## Governance',
    '',
    '- `bun run policy:audit` validates jurisdiction/sport/market references, active conflicts, block-alert coverage, and expiration.',
    '- `bun run jurisdictions:docs:check` fails when this document is stale.',
    '- Policy lifecycle and enforcement use the glossary key; SQLite is a materialized runtime index.',
    ''
  );
  return `${lines.join('\n').trimEnd()}\n`;
}

async function main(): Promise<void> {
  const root = joinPath(import.meta.dir, '..');
  const target = joinPath(root, JURISDICTIONS_DOC_PATH);
  const rendered = renderJurisdictionsDocs();
  if (Bun.argv.includes('--check')) {
    if (!(await Bun.file(target).exists())) {
      console.error(`❌ missing ${JURISDICTIONS_DOC_PATH}`);
      process.exit(1);
    }
    if ((await Bun.file(target).text()) !== rendered) {
      console.error(`❌ ${JURISDICTIONS_DOC_PATH} is stale`);
      process.exit(1);
    }
    console.log(`✅ ${JURISDICTIONS_DOC_PATH} current`);
    return;
  }
  await Bun.write(target, rendered);
  console.log(`✅ wrote ${JURISDICTIONS_DOC_PATH}`);
}

if (import.meta.main) await main();
