#!/usr/bin/env bun
// tools/simple-import-tracker.ts — Bun plugin for tracking imports

import { plugin } from "bun";

plugin({
  name: "simple import tracker",
  setup(build) {
    const transpiler = new Bun.Transpiler();
    const trackedImports: Record<string, number> = {};

    // Track all TypeScript files
    build.onLoad({ filter: /\.(ts|js)$/ }, async ({ path }) => {
      try {
        const contents = await Bun.file(path).arrayBuffer();
        const imports = transpiler.scanImports(contents);

        console.log(`📁 ${path}:`);

        for (const importInfo of imports) {
          const importPath = importInfo.path;
          trackedImports[importPath] = (trackedImports[importPath] || 0) + 1;
          console.log(`   📦 ${importPath} (${trackedImports[importPath]})`);
        }

        if (imports.length === 0) {
          console.log(`   (no imports)`);
        }
      } catch (error) {
        console.log(`❌ Error scanning ${path}:`, error.message);
      }

      // Return undefined to let Bun handle the file normally
      return undefined;
    });

    // Generate stats when requested
    build.onLoad({ filter: /import-stats\.js$/ }, async ({ defer }) => {
      console.log(`📊 Generating import statistics...`);

      // Wait for all files to be processed
      await defer();

      console.log(`📋 Final import statistics:`);
      Object.entries(trackedImports).forEach(([path, count]) => {
        console.log(`   ${path}: ${count} times`);
      });

      return {
        contents: `
// Import Statistics Generated by Plugin
const importStats = ${JSON.stringify(trackedImports, null, 2)};

console.log('🔍 Import Analysis Results:');
console.log('Total unique imports:', Object.keys(importStats).length);
console.log('');
Object.entries(importStats).forEach(([path, count]) => {
  console.log(\`  \${path}: \${count} import\${count === 1 ? '' : 's'}\`);
});

export default importStats;
        `,
        loader: "js",
      };
    });
  },
});
