/**
 * URLPattern analyzer configuration.
 */

export const ANALYZER_CONFIG = {
  WPT_TESTS_PASSED: 408,
  PERFORMANCE_ITERATIONS: 100,
  MEMORY_TEST_ITERATIONS: 50,
  PERFORMANCE_BOOST_ITERATIONS: 100,
  SLOW_EXEC_THRESHOLD: 10,
  HIGH_MEMORY_THRESHOLD: 10,
  SLOW_KEEPALIVE_THRESHOLD: 1000,
  AGENT_TEST_REQUESTS: 2,
  AGENT_COMPREHENSIVE_REQUESTS: 2,
  CACHE_TTL_MS: 5 * 60 * 1000,
  SKIP_EXTERNAL_CALLS: true,
  PROXY_DETECTION_TIMEOUT: 500,
} as const;
