// Default seed entries for BunMatrixViewer

import type { BunDocEntry } from "./types";

export const DEFAULT_ENTRIES: BunDocEntry[] = [
  {
    term: "Bun.file",
    path: "/docs/api/file-io",
    bunMinVersion: "0.1.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 1000000, baseline: "10x fs-extra" },
    security: { classification: "medium" },
    category: "io",
    relatedTerms: ["Bun.write", "Bun.read"],
  },
  {
    term: "Bun.password",
    path: "/docs/api/password",
    bunMinVersion: "1.0.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 50000, baseline: "Argon2id native" },
    security: { classification: "high", zeroTrust: true },
    category: "crypto",
    cliFlags: ["--no-argon2"],
  },
  {
    term: "Bun.serve",
    path: "/docs/api/http",
    bunMinVersion: "0.6.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 50000, baseline: "2.3x Express" },
    security: { classification: "medium" },
    category: "network",
    relatedTerms: ["Bun.fetch", "Bun.websocket"],
  },
  {
    term: "Bun.sqlite",
    path: "/docs/api/sqlite",
    bunMinVersion: "1.0.22",
    stability: "experimental",
    platforms: ["darwin", "linux"],
    perfProfile: { opsSec: 100000, baseline: "7.9x better-sqlite3" },
    security: { classification: "high" },
    category: "core",
    cliFlags: ["--experimental-sqlite"],
    changelogFeed: new URL("https://bun.sh/blog/rss.xml#tag=sqlite"),
  },
  {
    term: "Bun.inspect.table",
    path: "/docs/api/utils",
    bunMinVersion: "0.1.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    security: { classification: "low" },
    category: "cli",
  },
  {
    term: "Bun.CryptoHasher",
    path: "/docs/api/crypto",
    bunMinVersion: "0.5.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 500000, baseline: "3.2x Node crypto" },
    security: { classification: "high", zeroTrust: true },
    category: "crypto",
  },
  {
    term: "Bun.FFI",
    path: "/docs/api/ffi",
    bunMinVersion: "0.2.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    security: { classification: "high", requiresRoot: true },
    category: "ffi",
    relatedTerms: ["Bun.dlopen", "Bun.CPointer"],
  },
  {
    term: "Bun.gzip",
    path: "/docs/api/compression",
    bunMinVersion: "0.1.0",
    stability: "stable",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 100000, baseline: "5.4x Node zlib" },
    security: { classification: "low" },
    category: "core",
  },
  {
    term: "Bun.thuis",
    path: "/docs/api/thuis",
    bunMinVersion: "1.3.7",
    stability: "experimental",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 10000, baseline: "Home automation" },
    security: { classification: "medium" },
    category: "cli",
    thuisConfig: {
      homeDirectory: "~/.bun/thuis",
      configFile: "thuis.config.json",
      envVars: { THUIS_HOME: "~/.bun/thuis", THUIS_MODE: "daemon" },
      serviceMode: "daemon",
    },
    homeFeatures: {
      localServer: true,
      autoStart: true,
      trayIcon: true,
      notifications: true,
    },
    cliFlags: ["--thuis-daemon", "--thuis-config"],
    relatedTerms: ["Bun.serve", "Bun.file"],
  },
  {
    term: "Bun.home",
    path: "/docs/api/home",
    bunMinVersion: "1.3.7",
    stability: "experimental",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 50000, baseline: "Home directory manager" },
    security: { classification: "medium" },
    category: "cli",
    thuisConfig: {
      homeDirectory: process.env.HOME || process.env.USERPROFILE,
      configFile: ".bunhomerc",
      envVars: { BUN_HOME: "~/.bun", BUN_CONFIG: "~/.bun/config" },
      serviceMode: "cli",
    },
    homeFeatures: {
      localServer: false,
      autoStart: false,
      trayIcon: false,
      notifications: false,
    },
    cliFlags: ["--home", "--config"],
    relatedTerms: ["Bun.thuis", "Bun.file"],
  },
  {
    term: "Bun.thuis.serve",
    path: "/docs/api/thuis/serve",
    bunMinVersion: "1.3.7",
    stability: "experimental",
    platforms: ["darwin", "linux", "win32"],
    perfProfile: { opsSec: 30000, baseline: "Local home server" },
    security: { classification: "medium", zeroTrust: true },
    category: "network",
    thuisConfig: {
      homeDirectory: "~/.bun/thuis/server",
      configFile: "server.config.json",
      envVars: { THUIS_SERVER_PORT: "3000", THUIS_SSL: "true" },
      serviceMode: "daemon",
    },
    homeFeatures: {
      localServer: true,
      autoStart: true,
      trayIcon: true,
      notifications: true,
    },
    cliFlags: ["--port", "--ssl", "--thuis-serve"],
    relatedTerms: ["Bun.serve", "Bun.thuis"],
  },
  {
    term: "Bun.thuis.automate",
    path: "/docs/api/thuis/automate",
    bunMinVersion: "1.3.7",
    stability: "experimental",
    platforms: ["darwin", "linux"],
    perfProfile: { opsSec: 5000, baseline: "Task automation" },
    security: { classification: "high", requiresRoot: true },
    category: "cli",
    thuisConfig: {
      homeDirectory: "~/.bun/thuis/automation",
      configFile: "automation.yaml",
      envVars: { THUIS_AUTOMATE: "enabled", THUIS_SCHEDULE: "cron" },
      serviceMode: "daemon",
    },
    homeFeatures: {
      localServer: false,
      autoStart: true,
      trayIcon: true,
      notifications: true,
    },
    cliFlags: ["--schedule", "--thuis-automate"],
    relatedTerms: ["Bun.spawn", "Bun.thuis"],
  },
];
