#!/bin/bash
# Enhanced Multi-Tenant Dashboard - Environment Paths
# Generated by setup-paths.ts

# Base directories
export DASHBOARD_BASE_DIR="/Users/nolarose/mcp-tools"
export DASHBOARD_CONFIG_DIR="/Users/nolarose/mcp-tools/config"
export DASHBOARD_DATA_DIR="/Users/nolarose/mcp-tools/data"
export DASHBOARD_LOGS_DIR="/Users/nolarose/mcp-tools/logs"
export DASHBOARD_BACKUPS_DIR="/Users/nolarose/mcp-tools/backups"
export DASHBOARD_SNAPSHOTS_DIR="/Users/nolarose/mcp-tools/snapshots"
export DASHBOARD_AUDIT_DIR="/Users/nolarose/mcp-tools/audit-review"

# Database paths
export DASHBOARD_DB_DEV="/Users/nolarose/mcp-tools/data/dev-audit.db"
export DASHBOARD_DB_STAGING="/Users/nolarose/mcp-tools/data/staging-audit.db"
export DASHBOARD_DB_PROD="/Users/nolarose/mcp-tools/data/prod-audit.db"
export DASHBOARD_DB_TEST="/Users/nolarose/mcp-tools/data/test-audit.db"

# Configuration files
export DASHBOARD_ENV_DEV="/Users/nolarose/mcp-tools/config/.env.development"
export DASHBOARD_ENV_STAGING="/Users/nolarose/mcp-tools/config/.env.staging"
export DASHBOARD_ENV_PROD="/Users/nolarose/mcp-tools/config/.env.production"
export DASHBOARD_NGINX_CONF="/Users/nolarose/mcp-tools/config/nginx.conf"
export DASHBOARD_K8S_DEPLOY="/Users/nolarose/mcp-tools/config/k8s-deployment.yaml"
export DASHBOARD_SYSTEMD_SERVICE="/Users/nolarose/mcp-tools/config/dashboard.service"

# Log files
export DASHBOARD_LOG_APP="/Users/nolarose/mcp-tools/logs/dashboard.log"
export DASHBOARD_LOG_ACCESS="/Users/nolarose/mcp-tools/logs/access.log"
export DASHBOARD_LOG_ERROR="/Users/nolarose/mcp-tools/logs/error.log"
export DASHBOARD_LOG_AUDIT="/Users/nolarose/mcp-tools/logs/audit.log"
export DASHBOARD_LOG_PERF="/Users/nolarose/mcp-tools/logs/performance.log"

# Server URLs
export DASHBOARD_URL_DEV="http://localhost:3333/enhanced-dashboard.html"
export DASHBOARD_URL_STAGING="https://staging.yourdomain.com/enhanced-dashboard.html"
export DASHBOARD_URL_PROD="https://dashboard.yourdomain.com/enhanced-dashboard.html"

# Ports
export DASHBOARD_PORT_DEV="3333"
export DASHBOARD_PORT_STAGING="3334"
export DASHBOARD_PORT_PROD="3335"

# Core files
export DASHBOARD_SERVER="/Users/nolarose/mcp-tools/enhanced-dashboard.ts"
export DASHBOARD_UI="/Users/nolarose/mcp-tools/enhanced-dashboard.html"
export DASHBOARD_CLI="/Users/nolarose/mcp-tools/dashboard-cli.ts"
export DASHBOARD_DEPLOY="/Users/nolarose/mcp-tools/deploy.ts"

# Binary and executable paths
export DASHBOARD_BIN_DIR="/Users/nolarose/mcp-tools/bin"
export DASHBOARD_NODE_BIN="/Users/nolarose/.bun/bin"
export DASHBOARD_PYTHON_BIN="/usr/bin/python3"
export DASHBOARD_DOCKER_BIN="/usr/local/bin/docker"

# Script paths
export DASHBOARD_SCRIPTS_DIR="/Users/nolarose/mcp-tools/scripts"
export DASHBOARD_DEPLOY_SCRIPT="/Users/nolarose/mcp-tools/deploy.ts"
export DASHBOARD_BACKUP_SCRIPT="/Users/nolarose/mcp-tools/scripts/backup.sh"
export DASHBOARD_RESTORE_SCRIPT="/Users/nolarose/mcp-tools/scripts/restore.sh"

echo "✅ Enhanced Dashboard environment variables set"
echo "📁 Base Directory: $DASHBOARD_BASE_DIR"
echo "🔧 Config Directory: $DASHBOARD_CONFIG_DIR"
echo "💾 Data Directory: $DASHBOARD_DATA_DIR"
echo "📊 Logs Directory: $DASHBOARD_LOGS_DIR"
echo "💿 Backups Directory: $DASHBOARD_BACKUPS_DIR"
